export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  date: string
  readingTime: number
  category: string
  categoryColor: string
  heroImage?: string    // absolute URL — overrides auto-generated Unsplash image
  heroImageAlt?: string
  ctaHref?: string
  ctaText?: string
  ctaSubtext?: string
  relatedPages?: { label: string; href: string }[]
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug:          'how-to-get-remote-job-france-international',
    heroImage:     '/images/blog/hero-international-laptop.jpg',
    heroImageAlt:  'Laptop with globe — international remote job search',
    title:         'How to Get a Remote Job in France as an International Candidate (2026)',
    excerpt:       'France tech is international — but only in certain sectors and at certain company stages. Learn the legal structures, CV format, lettre de motivation rules, and which platforms French companies actually use to hire globally.',
    date:          '2026-08-28',
    readingTime:   9,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-france',
    ctaText:       'Browse French remote jobs →',
    ctaSubtext:    'Roles at French tech companies genuinely open to international candidates.',
    relatedPages: [
      { label: '🇫🇷 Remote Jobs in France',              href: '/remote-jobs-france' },
      { label: '📄 Resume Format by Country',            href: '/blog/resume-format-by-country' },
      { label: '🌍 10 Skills for International Hire',    href: '/blog/cross-border-remote-job-skills' },
    ],
  },
  {
    slug:          'remote-job-salary-by-country',
    heroImage:     '/images/blog/hero-salary-by-country.jpg',
    heroImageAlt:  'World map showing remote job salary ranges by country',
    title:         'Remote Job Salaries by Country: What International Candidates Can Realistically Expect (2026)',
    excerpt:       'Why the $150K posted salary is not your salary as a contractor, how to benchmark correctly across US, UK, Germany, France and Canada, and the red flags that signal a company is underpaying international hires.',
    date:          '2026-08-26',
    readingTime:   9,
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Find roles with transparent pay ranges →',
    ctaSubtext:    'JobConnect AI surfaces salary info and contractor vs employee status on every listing.',
    relatedPages: [
      { label: '🇺🇸 US Remote Jobs for Internationals',  href: '/blog/how-to-get-remote-job-usa-international' },
      { label: '🌍 10 Skills for International Hire',    href: '/blog/cross-border-remote-job-skills' },
      { label: '🎯 ATS Optimization Guide',              href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'how-to-get-remote-job-in-germany-as-foreigner',
    heroImage:     '/images/blog/hero-germany.jpg',
    heroImageAlt:  'Map of Europe with Germany highlighted and German flag',
    title:         'How to Get a Remote Job in Germany as a Foreign National (2026 Guide)',
    excerpt:       'Everything you need to know about the Lebenslauf format, professional photos, cover letters, and which platforms actually hire internationally.',
    date:          '2026-08-15',
    readingTime:   8,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-germany',
    ctaText:       'Browse German remote jobs →',
    ctaSubtext:    'Filter for roles genuinely open to international candidates.',
    relatedPages: [
      { label: '🇩🇪 Remote Jobs in Germany',        href: '/remote-jobs-germany' },
      { label: '📄 Resume Format by Country',        href: '/blog/resume-format-by-country' },
    ],
  },
  {
    slug:          'resume-format-by-country',
    heroImage:     '/images/blog/hero-laptop-world.jpg',
    heroImageAlt:  'Laptop displaying a world map at a remote work desk',
    title:         'Resume Format by Country: US vs UK vs Germany vs France vs Canada',
    excerpt:       'A practical comparison of what hiring managers in 5 countries expect — photos, length, tone, personal information, and the differences that trip up international applicants.',
    date:          '2026-08-10',
    readingTime:   6,
    category:      'Resume Tips',
    categoryColor: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
    ctaHref:       '/ai-tools/resume-builder',
    ctaText:       'Build your country-specific resume →',
    ctaSubtext:    'AI resume builder that adapts to US, UK, German, French, and Canadian formats.',
    relatedPages: [
      { label: '🇩🇪 Remote Jobs in Germany', href: '/remote-jobs-germany' },
      { label: '🇫🇷 Remote Jobs in France',  href: '/remote-jobs-france' },
      { label: '🇬🇧 Remote Jobs in the UK',  href: '/remote-jobs-uk' },
    ],
  },
  {
    slug:          'how-to-spot-fake-remote-jobs',
    heroImage:     '/images/blog/hero-remote-desk.jpg',
    heroImageAlt:  'Laptop and coffee on a desk — remote work setup',
    title:         "How to Tell if a Remote Job Actually Hires Internationally (and Which Don't)",
    excerpt:       'The exact phrases to look for, the red flags that cost you hours of wasted applications, and how our Remote-Friendly Detector automates this for you.',
    date:          '2026-08-05',
    readingTime:   5,
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Search pre-filtered remote jobs →',
    ctaSubtext:    'Every listing run through our Remote-Friendly Detector before you see it.',
    relatedPages: [
      { label: '🎯 ATS Tips for International Candidates', href: '/blog/ats-resume-international-candidates' },
      { label: '🌍 10 Skills That Make You Hireable',      href: '/blog/cross-border-remote-job-skills' },
    ],
  },
  {
    slug:          'how-to-get-remote-job-canada-international',
    heroImage:     '/images/blog/hero-canada.jpg',
    heroImageAlt:  'Map of North America with Canada highlighted and Canadian flag',
    title:         'How to Get a Remote Job in Canada as an International Candidate (2026)',
    excerpt:       "Canada actively recruits global tech talent — but the rules differ from the US. Here's everything you need to know about work permits, bilingual advantage, and the Canadian application style.",
    date:          '2026-08-22',
    readingTime:   8,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-canada',
    ctaText:       'Browse Canadian remote jobs →',
    ctaSubtext:    'Roles filtered for international candidates — contractor and employee.',
    relatedPages: [
      { label: '🇨🇦 Remote Jobs in Canada',   href: '/remote-jobs-canada' },
      { label: '🇺🇸 Remote Jobs in the USA',   href: '/remote-jobs-usa' },
      { label: '📄 Resume Format by Country',  href: '/blog/resume-format-by-country' },
    ],
  },
  {
    slug:          'remote-work-france-foreigner',
    heroImage:     '/images/blog/hero-france.jpg',
    heroImageAlt:  'Map of Europe with France highlighted and French flag',
    title:         'Working Remotely for a French Company as a Foreigner: What You Need to Know',
    excerpt:       'French professional culture, the CV format with no photo, the art of the lettre de motivation, and the platforms where international candidates actually find French remote roles.',
    date:          '2026-08-20',
    readingTime:   7,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-france',
    ctaText:       'Browse French remote jobs →',
    ctaSubtext:    'French companies that genuinely hire international remote workers.',
    relatedPages: [
      { label: '🇫🇷 Remote Jobs in France',         href: '/remote-jobs-france' },
      { label: '📄 Resume Format by Country',        href: '/blog/resume-format-by-country' },
    ],
  },
  {
    slug:          'cross-border-remote-job-skills',
    heroImage:     '/images/blog/hero-cross-border-skills.jpg',
    heroImageAlt:  'Globe with connection lines — cross-border remote skills',
    title:         'The 10 Skills That Make You Hireable Internationally (For Remote Jobs)',
    excerpt:       'Technical skills get you through the door. These 10 cross-border skills determine whether a company in Germany, Canada, or the UK actually hires you over a local candidate.',
    date:          '2026-08-18',
    readingTime:   6,
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Find remote jobs matching your skills →',
    ctaSubtext:    'AI-matched remote roles for international candidates.',
    relatedPages: [
      { label: '🎯 ATS Optimization Guide',        href: '/blog/ats-resume-international-candidates' },
      { label: '🌍 Remote-Friendly Job Checklist', href: '/blog/how-to-spot-fake-remote-jobs' },
    ],
  },
  {
    slug:          'ats-resume-international-candidates',
    heroImage:     '/images/blog/hero-ats-resume.jpg',
    heroImageAlt:  'ATS resume scanning icon with orbit rings',
    title:         'ATS Optimization for International Candidates: Why Your Resume Gets Rejected',
    excerpt:       'Most international candidates are filtered out before a human ever reads their resume. Here is exactly how ATS systems work, why international resumes fail, and how to fix yours.',
    date:          '2026-08-16',
    readingTime:   6,
    category:      'Resume Tips',
    categoryColor: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
    ctaHref:       '/ai-tools/resume-builder',
    ctaText:       'Build your ATS-optimized resume →',
    ctaSubtext:    'Our AI resume builder formats your CV to pass international ATS filters.',
    relatedPages: [
      { label: '📄 Resume Format by Country',       href: '/blog/resume-format-by-country' },
      { label: '🌍 10 Skills for International Hire', href: '/blog/cross-border-remote-job-skills' },
    ],
  },
  {
    slug:          'how-to-get-remote-job-usa-international',
    heroImage:     '/images/blog/hero-usa.jpg',
    heroImageAlt:  'Map of North America with USA highlighted and American flag',
    title:         'How to Get a Remote Job in the USA as an International Candidate (2026)',
    excerpt:       'The US is the largest remote job market — but most listings exclude non-US candidates by default. Learn W-2 vs 1099 vs Corp-to-Corp, how to detect genuinely international-open roles, and how to position yourself to win.',
    date:          '2026-08-24',
    readingTime:   10,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-usa',
    ctaText:       'Browse US remote jobs open to internationals →',
    ctaSubtext:    'Pre-filtered for C2C, EOR-supported, and global-remote US roles.',
    relatedPages: [
      { label: '🇺🇸 Remote Jobs in the USA',              href: '/remote-jobs-usa' },
      { label: '🎯 ATS Optimization for Internationals',  href: '/blog/ats-resume-international-candidates' },
      { label: '🔍 Spot Roles That Actually Hire Globally', href: '/blog/how-to-spot-fake-remote-jobs' },
    ],
  },
  {
    slug:          'remote-job-uk-international',
    heroImage:     '/images/blog/hero-uk.jpg',
    heroImageAlt:  'Map of Europe with UK highlighted and British flag',
    title:         'How to Land a Remote Job in the UK as a Non-UK Resident (2026)',
    excerpt:       "Post-Brexit, right-to-work rules, British CV format, and which UK sectors genuinely hire international remote workers — everything you need to run a smart UK job search.",
    date:          '2026-08-14',
    readingTime:   8,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-uk',
    ctaText:       'Browse UK remote jobs →',
    ctaSubtext:    'UK companies filtered for international candidates — with right-to-work clarity.',
    relatedPages: [
      { label: '🇬🇧 Remote Jobs in the UK',         href: '/remote-jobs-uk' },
      { label: '📄 Resume Format by Country',        href: '/blog/resume-format-by-country' },
      { label: '🎯 ATS Optimization Guide',          href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'how-to-find-remote-job-from-vietnam-2026',
    title:         'How to Find a Remote Job From Vietnam in 2026: The Complete Strategy',
    excerpt:       "Vietnam's tech workforce is internationally competitive — but visibility and positioning are the real challenges. A complete guide to platforms, timezone advantage, sectors, CV formatting, and getting paid across borders.",
    date:          '2026-09-02',
    readingTime:   9,
    heroImage:     '/images/blog/remote-job-vietnam.jpg',
    heroImageAlt:  'Laptop with Ho Chi Minh City skyline — remote work from Vietnam',
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/jobs',
    ctaText:       'Browse remote jobs open to Vietnam →',
    ctaSubtext:    'Verified international remote listings with explicit location filtering.',
    relatedPages: [
      { label: '🌍 Cross-Border Remote Jobs Guide',       href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '📄 Resume Format by Country',             href: '/blog/resume-format-by-country' },
      { label: '🎯 ATS Optimization for Internationals',  href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'trouver-emploi-remote-depuis-etranger',
    title:         "Trouver un Emploi Remote depuis l'Étranger : Guide Pratique Multi-Marchés (2026)",
    excerpt:       "Comment trouver des offres réellement ouvertes aux candidats étrangers, choisir le bon statut contractuel, rédiger une candidature qui rassure les recruteurs, et recevoir son salaire depuis l'étranger.",
    date:          '2026-09-04',
    readingTime:   9,
    heroImage:     '/images/blog/emploi-remote-etranger.jpg',
    heroImageAlt:  'Professionnelle travaillant sur ordinateur portable avec carte du monde en arrière-plan',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Parcourir les offres remote internationales →',
    ctaSubtext:    "Offres vérifiées avec filtrage géographique explicite pour les candidats basés à l'étranger.",
    relatedPages: [
      { label: '🌍 Guide complet du remote transfrontalier',     href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: "⚖️ Travailler à distance pour l'étranger",      href: '/blog/travailler-distance-entreprise-etrangere' },
      { label: '📄 Postuler sans déménager',                    href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'cross-border-remote-jobs-complete-guide',
    title:         'Cross-Border Remote Jobs: The Complete A-to-Z Guide (Find, Apply, Negotiate, Sign)',
    excerpt:       'Every step of landing an international remote job without relocating — from finding genuinely open listings to understanding what you are signing. The process is a skill, and this guide teaches it.',
    date:          '2026-09-08',
    readingTime:   11,
    heroImage:     '/images/blog/cross-border-remote-guide.jpg',
    heroImageAlt:  'World map with coloured country flags connected by glowing lines — cross-border remote work',
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Find your next cross-border role →',
    ctaSubtext:    'International remote listings verified for genuine location openness.',
    relatedPages: [
      { label: '🔍 Spot Roles That Actually Hire Globally',  href: '/blog/how-to-spot-fake-remote-jobs' },
      { label: '🌍 10 Skills for International Hire',        href: '/blog/cross-border-remote-job-skills' },
      { label: '🎯 ATS Optimization Guide',                  href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'travailler-distance-entreprise-etrangere',
    title:         'Travailler à Distance pour une Entreprise Étrangère : Contrats, Paiement, Fiscalité (2026)',
    excerpt:       "Tout ce qu'il faut savoir sur les structures contractuelles internationales, la réception de paiements étrangers via Wise ou EOR, la fiscalité des revenus étrangers, et la protection sociale quand l'employeur est à l'étranger.",
    date:          '2026-09-10',
    readingTime:   10,
    heroImage:     '/images/blog/travailler-entreprise-etrangere.jpg',
    heroImageAlt:  'Main signant un contrat numérique avec devises internationales euro livre yen en arrière-plan',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Trouver une offre remote internationale →',
    ctaSubtext:    "Offres d'entreprises déjà équipées pour recruter à l'international.",
    relatedPages: [
      { label: "🌍 Trouver un emploi remote depuis l'étranger",  href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '📄 Postuler sans déménager',                     href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'best-remote-jobs-french-speakers-2026',
    title:         'Best Remote Jobs for French Speakers in 2026: Sectors, Companies, and Salaries',
    excerpt:       'French-English bilingualism is a premium qualification in international remote hiring. A sector-by-sector breakdown of where demand is highest, which companies recruit bilingual talent most actively, and how to position the advantage correctly.',
    date:          '2026-09-12',
    readingTime:   9,
    heroImage:     '/images/blog/remote-jobs-french-speakers.jpg',
    heroImageAlt:  'France and Canada flags connected to Africa by glowing arcs — Francophone remote job market',
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Browse remote jobs requiring French →',
    ctaSubtext:    'Filter for bilingual FR/EN roles at international companies.',
    relatedPages: [
      { label: '🇫🇷 Remote Jobs in France',                        href: '/remote-jobs-france' },
      { label: '🇨🇦 Remote Jobs in Canada',                        href: '/remote-jobs-canada' },
      { label: '🌍 Meilleurs emplois remote francophones 2026',    href: '/blog/meilleurs-emplois-remote-francophones-2026' },
    ],
  },
  {
    slug:          'meilleurs-emplois-remote-francophones-2026',
    title:         'Meilleurs Emplois Remote pour les Francophones en 2026 : Secteurs, Salaires et Plateformes',
    excerpt:       "Guide complet pour les professionnels francophones d'Afrique subsaharienne, d'Haïti et des DOM-TOM : secteurs porteurs, niveaux de rémunération réalistes, plateformes efficaces et stratégie de candidature.",
    date:          '2026-09-16',
    readingTime:   10,
    heroImage:     '/images/blog/emplois-remote-francophones.jpg',
    heroImageAlt:  "Carte numérique montrant l'Afrique connectée à l'Europe et aux Amériques — emploi remote francophone",
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Parcourir les offres remote francophones →',
    ctaSubtext:    'Offres avec filtrage linguistique pour les candidats francophones.',
    relatedPages: [
      { label: "🌍 Trouver un emploi remote depuis l'étranger",      href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '🌐 Best remote jobs for French speakers',             href: '/blog/best-remote-jobs-french-speakers-2026' },
      { label: "⚖️ Travailler à distance pour une entreprise étrangère", href: '/blog/travailler-distance-entreprise-etrangere' },
    ],
  },
  {
    slug:          'international-jobs-without-relocating',
    title:         "International Jobs Without Relocating: How to Win Remote Arrangements Employers Don't Advertise",
    excerpt:       "Most 'must be on-site' postings are negotiable. How to screen job listings before applying, make the case for full remote during the process, and negotiate location at the moment of maximum leverage — without burning the relationship.",
    date:          '2026-09-18',
    readingTime:   9,
    heroImage:     '/images/blog/international-jobs-no-relocation.jpg',
    heroImageAlt:  'Person working from home with world map and location pins — international jobs without relocating',
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Find remote-friendly international roles →',
    ctaSubtext:    "Remote-Friendly Detector surfaces companies already distributed — even when postings don't say so.",
    relatedPages: [
      { label: '🔍 Spot Roles That Actually Hire Globally',  href: '/blog/how-to-spot-fake-remote-jobs' },
      { label: '🌍 Cross-Border Remote Jobs Guide',          href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '📄 Postuler sans déménager (FR)',            href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'postuler-emploi-international-sans-demenager',
    title:         'Postuler à un Emploi International Sans Déménager : Candidature Remote-First et Négociation (2026)',
    excerpt:       "Comment lire une offre 'sur site' comme un recruteur, présenter une candidature remote-first sans perdre en crédibilité, et négocier un arrangement de télétravail au moment de l'offre avec les arguments qui convainquent les recruteurs européens.",
    date:          '2026-09-22',
    readingTime:   10,
    heroImage:     '/images/blog/postuler-international-sans-demenager.jpg',
    heroImageAlt:  'Maison connectée au globe numérique — postuler à un emploi international sans déménager',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Trouver une offre internationale négociable →',
    ctaSubtext:    "Offres avec signaux d'ouverture au travail distribué affichés sur chaque fiche.",
    relatedPages: [
      { label: "🌍 Trouver un emploi remote depuis l'étranger",  href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '🌐 International jobs without relocating (EN)',   href: '/blog/international-jobs-without-relocating' },
      { label: "⚖️ Travailler à distance pour l'étranger",       href: '/blog/travailler-distance-entreprise-etrangere' },
    ],
  },
  {
    slug:          'remote-jobs-africa-global-companies',
    title:         'Remote Jobs in Africa: How to Work for Global Companies from Senegal, Côte d\'Ivoire, Cameroon',
    excerpt:       "The infrastructure for African professionals to work for European and North American companies without relocating — EOR platforms, multi-currency payments, distributed team practices — has matured to the point where geography is increasingly a preference, not a constraint.",
    date:          '2026-10-02',
    readingTime:   10,
    heroImage:     '/images/blog/remote-jobs-africa.jpg',
    heroImageAlt:  'Laptop with world map overlay against an African coastal city skyline at dusk',
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/jobs',
    ctaText:       'Browse remote jobs open to African candidates →',
    ctaSubtext:    'Verified international listings with explicit location filtering for African-based professionals.',
    relatedPages: [
      { label: '🌍 Best Remote Jobs for French Speakers',       href: '/blog/best-remote-jobs-french-speakers-2026' },
      { label: '🌍 Meilleurs emplois remote francophones',      href: '/blog/meilleurs-emplois-remote-francophones-2026' },
      { label: '🌐 Cross-Border Remote Jobs Complete Guide',    href: '/blog/cross-border-remote-jobs-complete-guide' },
    ],
  },
  {
    slug:          'emploi-remote-afrique-entreprises-mondiales',
    title:         'Emploi remote en Afrique : travailler pour des entreprises mondiales depuis chez soi',
    excerpt:       "Guide complet pour les professionnels d'Afrique francophone : secteurs ouverts, plateformes qui fonctionnent, paiement via Wave/Mobile Money/Wise, fiscalité locale, et comment construire une candidature crédible pour une entreprise mondiale.",
    date:          '2026-10-06',
    readingTime:   10,
    heroImage:     '/images/blog/emploi-remote-afrique.jpg',
    heroImageAlt:  'Professionnel africain travaillant sur ordinateur portable avec carte du monde connectée en arrière-plan',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Parcourir les offres remote internationales →',
    ctaSubtext:    "Offres vérifiées avec filtrage géographique pour les candidats basés en Afrique francophone.",
    relatedPages: [
      { label: '🌍 Meilleurs emplois remote francophones 2026',  href: '/blog/meilleurs-emplois-remote-francophones-2026' },
      { label: '🌐 Remote Jobs in Africa (EN)',                  href: '/blog/remote-jobs-africa-global-companies' },
      { label: "⚖️ Travailler à distance pour l'étranger",      href: '/blog/travailler-distance-entreprise-etrangere' },
    ],
  },
  {
    slug:          'visa-friendly-remote-jobs-employers-accept',
    title:         'Visa-Friendly Remote Jobs: What Employers Actually Accept',
    excerpt:       "Most international candidates misunderstand the visa question for remote work. The difference between contractor and employment arrangements changes everything — and 57 countries now have legal frameworks specifically designed for remote workers.",
    date:          '2026-10-09',
    readingTime:   9,
    heroImage:     '/images/blog/visa-friendly-remote-jobs.jpg',
    heroImageAlt:  'Passport and credit card with glowing global network — visa-friendly remote work',
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Find remote roles open to your location →',
    ctaSubtext:    'Remote-Friendly Detector shows companies with existing international hiring infrastructure.',
    relatedPages: [
      { label: '🌐 Cross-Border Remote Jobs Complete Guide',    href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '🌍 International Jobs Without Relocating',     href: '/blog/international-jobs-without-relocating' },
      { label: '⚖️ Emploi remote et visa (FR)',                href: '/blog/emploi-remote-visa-employeurs-acceptent' },
    ],
  },
  {
    slug:          'emploi-remote-visa-employeurs-acceptent',
    title:         "Emploi remote et visa : ce que les employeurs acceptent vraiment",
    excerpt:       "Statut auto-entrepreneur, portage salarial, EOR : les trois structures pour travailler en remote pour une entreprise étrangère depuis la France, la Belgique ou la Suisse, et comment rassurer un employeur européen sur votre statut légal.",
    date:          '2026-10-13',
    readingTime:   9,
    heroImage:     '/images/blog/emploi-remote-visa-europe.jpg',
    heroImageAlt:  'Architecture européenne nocturne avec contrat numérique lumineux — emploi remote et visa',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Trouver une offre remote compatible avec votre statut →',
    ctaSubtext:    "Offres d'entreprises ayant déjà une infrastructure de recrutement international.",
    relatedPages: [
      { label: '⚖️ Visa-Friendly Remote Jobs (EN)',            href: '/blog/visa-friendly-remote-jobs-employers-accept' },
      { label: "🌍 Trouver un emploi remote depuis l'étranger", href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '📄 Postuler sans déménager',                   href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'how-ai-job-matching-works',
    title:         'How AI Job Matching Works: Finding Roles That Fit Your Real Profile',
    excerpt:       "75% of international resumes are rejected by ATS before a human reads them. Understanding how matching algorithms actually work — and why they systematically disadvantage international candidates — is the first step to beating the system.",
    date:          '2026-10-16',
    readingTime:   9,
    heroImage:     '/images/blog/ai-job-matching.jpg',
    heroImageAlt:  'Diverse candidate profiles connected by glowing AI matching lines to a central point',
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'See roles matched to your real profile →',
    ctaSubtext:    'Cross-border AI matching calibrated for international candidates, not domestic hiring patterns.',
    relatedPages: [
      { label: '🎯 ATS Optimization for International Candidates', href: '/blog/ats-resume-international-candidates' },
      { label: '🤖 Comment fonctionne le matching IA (FR)',         href: '/blog/matching-ia-emploi-comment-ca-marche' },
      { label: '🌍 Cross-Border Remote Jobs Guide',                 href: '/blog/cross-border-remote-jobs-complete-guide' },
    ],
  },
  {
    slug:          'matching-ia-emploi-comment-ca-marche',
    title:         "Comment fonctionne le matching IA pour l'emploi",
    excerpt:       "Les CVs français sont rejetés à un taux 35 % supérieur aux CVs anglophones par les ATS conventionnels. Comprendre pourquoi et comment y remédier concrètement pour maximiser sa visibilité auprès des employeurs internationaux.",
    date:          '2026-10-20',
    readingTime:   9,
    heroImage:     '/images/blog/matching-ia-emploi.jpg',
    heroImageAlt:  "Profils de candidats africains connectés par IA avec skyline africaine — matching IA pour l'emploi",
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Trouver des offres matchées à votre profil réel →',
    ctaSubtext:    "Matching cross-border calibré pour les candidats francophones, pas uniquement pour les marchés anglophones.",
    relatedPages: [
      { label: '🤖 How AI Job Matching Works (EN)',             href: '/blog/how-ai-job-matching-works' },
      { label: '🎯 ATS et CV internationaux',                   href: '/blog/ats-resume-international-candidates' },
      { label: "🌍 Trouver un emploi remote depuis l'étranger", href: '/blog/trouver-emploi-remote-depuis-etranger' },
    ],
  },
  {
    slug:          'remote-job-interview-prep-international-candidate',
    title:         'Remote Job Interview Prep: How to Stand Out as an International Candidate',
    excerpt:       "67% of international remote workers say the interview — not the application — is where they felt most disadvantaged by their status. A systematic framework for handling the logistical conversation, technical setup, behavioral questions, and cultural communication in cross-border interviews.",
    date:          '2026-10-23',
    readingTime:   10,
    heroImage:     '/images/blog/remote-interview-prep.jpg',
    heroImageAlt:  'Professional in suit with headset, laptop and camera on tripod — remote interview setup',
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/ai-tools/interview-prep',
    ctaText:       'Practice with AI Interview Prep →',
    ctaSubtext:    'Simulated interviews calibrated for the cross-border remote hiring context.',
    relatedPages: [
      { label: '🎤 Préparer un entretien remote international (FR)', href: '/blog/preparer-entretien-emploi-remote-international' },
      { label: '🌍 Cross-Border Remote Jobs Guide',                   href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '🤖 How AI Job Matching Works',                        href: '/blog/how-ai-job-matching-works' },
    ],
  },
  {
    slug:          'preparer-entretien-emploi-remote-international',
    title:         "Préparer un entretien pour un emploi remote international",
    excerpt:       "71 % des candidats francophones citent la barrière de la langue comme principale source de stress en entretien international. Un guide pratique pour gérer l'entretien en anglais, répondre aux questions difficiles sur la localisation et le statut légal, et éviter les erreurs classiques.",
    date:          '2026-10-27',
    readingTime:   10,
    heroImage:     '/images/blog/preparer-entretien-remote.jpg',
    heroImageAlt:  "Candidat francophone en entretien vidéo avec casque, skyline africaine nocturne en arrière-plan",
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/ai-tools/interview-prep',
    ctaText:       "S'entraîner avec l'outil Interview Prep →",
    ctaSubtext:    "Simulations d'entretiens calibrées pour le recrutement remote international.",
    relatedPages: [
      { label: '🎤 Remote Job Interview Prep (EN)',             href: '/blog/remote-job-interview-prep-international-candidate' },
      { label: "🌍 Trouver un emploi remote depuis l'étranger", href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '📄 Postuler sans déménager',                   href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },

  // --- November 2026 ---
  {
    slug:          'hire-remote-talent-globally-without-local-entity',
    title:         'How to Hire Remote Talent Globally Without a Local Entity',
    excerpt:       "74% of companies that expanded their remote hiring internationally did so without a local entity, using EOR services instead. A practical employer guide to EOR vs. contractor models, platform comparisons, compliance risks, and real-world examples from Africa and Asia.",
    date:          '2026-11-03',
    readingTime:   11,
    heroImage:     '/images/blog/hire-remote-talent-globally.jpg',
    heroImageAlt:  'Glowing world map with cyan location pins connected across all continents — global remote hiring network',
    category:      'Recruitment',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/recruiter',
    ctaText:       'Post a Job with Code EMPLOYER2026 →',
    ctaSubtext:    'Connect with pre-screened international remote candidates in 150+ countries.',
    relatedPages: [
      { label: '🌍 Recruter des talents remote (FR)',        href: '/blog/recruter-talents-remote-monde-entier' },
      { label: '📋 Cross-Border Remote Jobs Guide',          href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '🔎 State of Cross-Border Remote Work 2026', href: '/blog/state-of-cross-border-remote-work-2026' },
    ],
  },
  {
    slug:          'recruter-talents-remote-monde-entier',
    title:         'Comment recruter des talents à distance dans le monde entier',
    excerpt:       "61 % des dirigeants de PME francophones ont envisagé de recruter à l'international, mais 54 % y ont renoncé faute de connaissance des options disponibles. Guide complet : portage salarial, EOR, contractor, plateformes et aspects légaux pour employeurs français, belges et suisses.",
    date:          '2026-11-05',
    readingTime:   10,
    heroImage:     '/images/blog/recruter-talents-remote-mondial.jpg',
    heroImageAlt:  'Carte du monde avec épingles de localisation cyan et bureaux virtuels de part et autre — recruter des talents remote à l\'international',
    category:      'Recrutement',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/recruiter',
    ctaText:       'Publier une offre avec le code EMPLOYER2026 →',
    ctaSubtext:    'Connectez-vous avec des talents internationaux présélectionnés dans plus de 150 pays.',
    relatedPages: [
      { label: '🌍 Hire Remote Talent Globally (EN)',        href: '/blog/hire-remote-talent-globally-without-local-entity' },
      { label: "📋 Guide cross-border complet",              href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '📊 Télétravail international 2026',          href: '/blog/teletravail-international-2026-etat-des-lieux' },
    ],
  },
  {
    slug:          'skill-gap-analysis-remote-jobs-guide',
    title:         'Skill Gap Analysis Before Applying: Why It Matters for Remote Jobs',
    excerpt:       "63% of rejected applications had candidates whose core qualifications matched the role — but whose self-assessment of adjacent skills was inaccurate. A guide to doing gap analysis before you apply: a 30-minute framework, free tools, and how to prioritize gaps by market demand.",
    date:          '2026-11-10',
    readingTime:   10,
    heroImage:     '/images/blog/skill-gap-analysis-remote.jpg',
    heroImageAlt:  'Neon radar chart with concentric polygon layers on dark background — visual skills gap analysis',
    category:      'Career Development',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/ai-tools/skill-gap',
    ctaText:       'Analyze Your Skill Gap →',
    ctaSubtext:    'Get a personalized gap analysis against real remote job descriptions in your field.',
    relatedPages: [
      { label: '🔍 Analyse de compétences avant postuler (FR)', href: '/blog/analyse-competences-avant-postuler' },
      { label: '📄 ATS Resume Guide',                           href: '/blog/ats-resume-international-candidates' },
      { label: '🤖 How AI Job Matching Works',                  href: '/blog/how-ai-job-matching-works' },
    ],
  },
  {
    slug:          'analyse-competences-avant-postuler',
    title:         'Analyse de compétences avant de postuler : pourquoi c\'est crucial',
    excerpt:       "59 % des candidats francophones dont le profil correspondait aux exigences du poste ont été rejetés en présélection, faute d'avoir identifié les compétences secondaires de leur parcours. Guide pratique avec exemples concrets, plan d'action en 4 semaines et outils gratuits.",
    date:          '2026-11-12',
    readingTime:   10,
    heroImage:     '/images/blog/analyse-competences-postuler.jpg',
    heroImageAlt:  "Radar de compétences avec silhouette de la Tour Eiffel et motif arabesque — analyse de gap pour les candidats francophones",
    category:      'Développement Carrière',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/ai-tools/skill-gap',
    ctaText:       'Analyser mes compétences →',
    ctaSubtext:    "Obtenez une analyse personnalisée de vos gaps par rapport aux offres réelles de votre marché cible.",
    relatedPages: [
      { label: '🔍 Skill Gap Analysis Before Applying (EN)', href: '/blog/skill-gap-analysis-remote-jobs-guide' },
      { label: '📄 ATS et candidats internationaux',         href: '/blog/ats-resume-international-candidates' },
      { label: '🤖 Matching IA pour l\'emploi',             href: '/blog/matching-ia-emploi-comment-ca-marche' },
    ],
  },
  {
    slug:          'linkedin-profile-optimization-international-jobs',
    title:         'LinkedIn Profile Optimization for International Job Seekers',
    excerpt:       "Profiles with a location-agnostic headline, English summary, and remote Open to Work receive 4.2x more recruiter outreach from international companies. A step-by-step guide to headline, summary, keywords, remote signals, and the classic mistakes non-anglophone profiles make.",
    date:          '2026-11-17',
    readingTime:   10,
    heroImage:     '/images/blog/linkedin-profile-international.jpg',
    heroImageAlt:  'Laptop displaying a schematic professional profile with photo, headline and skill fields — LinkedIn optimization for international jobs',
    category:      'Career Advice',
    categoryColor: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
    ctaHref:       '/ai-tools/career-coach',
    ctaText:       'Get LinkedIn Profile Feedback →',
    ctaSubtext:    'Personalized LinkedIn recommendations for international job seekers.',
    relatedPages: [
      { label: '💼 Profil LinkedIn international (FR)',   href: '/blog/optimiser-profil-linkedin-emploi-international' },
      { label: '📄 ATS Resume for International Candidates', href: '/blog/ats-resume-international-candidates' },
      { label: '🤖 How AI Job Matching Works',           href: '/blog/how-ai-job-matching-works' },
    ],
  },
  {
    slug:          'optimiser-profil-linkedin-emploi-international',
    title:         "Optimiser son profil LinkedIn pour décrocher un emploi international",
    excerpt:       "Les profils francophones avec un résumé en anglais reçoivent 3,8 fois plus de sollicitations de recruteurs internationaux. Guide complet : quand passer en anglais, rédiger un titre efficace, présenter son expérience pour un recruteur étranger, mots-clés et paramètres à configurer.",
    date:          '2026-11-19',
    readingTime:   9,
    heroImage:     '/images/blog/linkedin-profil-emploi-international.jpg',
    heroImageAlt:  "MacBook flottant affichant un dashboard de profil LinkedIn avec photo et indicateurs — optimisation pour l'emploi international",
    category:      'Conseils Carrière',
    categoryColor: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
    ctaHref:       '/ai-tools/career-coach',
    ctaText:       'Optimiser mon profil LinkedIn →',
    ctaSubtext:    "Recommandations personnalisées pour votre profil LinkedIn et votre recherche d'emploi international.",
    relatedPages: [
      { label: '💼 LinkedIn Optimization (EN)',            href: '/blog/linkedin-profile-optimization-international-jobs' },
      { label: '🤖 Matching IA pour l\'emploi',           href: '/blog/matching-ia-emploi-comment-ca-marche' },
      { label: "🌍 Trouver un emploi remote depuis l'étranger", href: '/blog/trouver-emploi-remote-depuis-etranger' },
    ],
  },
  {
    slug:          'state-of-cross-border-remote-work-2026',
    title:         'The State of Cross-Border Remote Work in 2026',
    excerpt:       "34 million professionals now work cross-border remotely — a 280% increase since 2021. A data-driven report on which countries are hiring, which sectors drive demand, salary benchmarks by region, the regulatory landscape, and what candidates should expect in 2027.",
    date:          '2026-11-24',
    readingTime:   11,
    heroImage:     '/images/blog/state-cross-border-remote-2026.jpg',
    heroImageAlt:  'Neon bar charts and upward trend line alongside connected world map — cross-border remote work growth data 2026',
    category:      'Industry Trends',
    categoryColor: 'bg-rose-100 dark:bg-rose-900/40 text-rose-700 dark:text-rose-300',
    ctaHref:       '/jobs',
    ctaText:       'Browse International Remote Jobs →',
    ctaSubtext:    'Find remote roles genuinely open to international candidates, with AI-powered application tools.',
    relatedPages: [
      { label: '📊 Télétravail international 2026 (FR)',        href: '/blog/teletravail-international-2026-etat-des-lieux' },
      { label: '🌍 Cross-Border Remote Jobs: Complete Guide',   href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '🤖 How AI Job Matching Works',                  href: '/blog/how-ai-job-matching-works' },
    ],
  },
  {
    slug:          'teletravail-international-2026-etat-des-lieux',
    title:         'Le télétravail international en 2026 : état des lieux',
    excerpt:       "28 millions de professionnels francophones travaillent désormais à distance pour des employeurs étrangers, avec l'Afrique subsaharienne représentant 41 % de la croissance. Analyse complète : salaires, secteurs en demande, opportunités pour Haïti, les DOM-TOM et la diaspora.",
    date:          '2026-11-26',
    readingTime:   11,
    heroImage:     '/images/blog/teletravail-international-2026.jpg',
    heroImageAlt:  "Planisphère avec Afrique et Europe illuminées en cyan et lignes de connexion — télétravail international francophone 2026",
    category:      'Tendances du Marché',
    categoryColor: 'bg-rose-100 dark:bg-rose-900/40 text-rose-700 dark:text-rose-300',
    ctaHref:       '/jobs',
    ctaText:       'Voir les offres remote internationales →',
    ctaSubtext:    "Des opportunités filtrées pour les candidats francophones, avec des outils de candidature en français.",
    relatedPages: [
      { label: '📊 State of Cross-Border Remote Work 2026 (EN)', href: '/blog/state-of-cross-border-remote-work-2026' },
      { label: "🌍 Trouver un emploi remote depuis l'étranger",  href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '🏢 Emploi remote : Afrique et entreprises mondiales', href: '/blog/emploi-remote-afrique-entreprises-mondiales' },
    ],
  },
]

export function getPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug)
}

// Slug → Unsplash search keywords for auto-generated images
const SLUG_KEYWORDS: Record<string, string> = {
  'how-to-get-remote-job-in-germany-as-foreigner': 'germany,berlin,remote,work',
  'resume-format-by-country':                      'resume,laptop,desk,professional',
  'how-to-spot-fake-remote-jobs':                  'job,search,laptop,coffee,focus',
  'how-to-get-remote-job-canada-international':    'canada,toronto,remote,work',
  'remote-work-france-foreigner':                  'paris,france,remote,work',
  'cross-border-remote-job-skills':                'teamwork,collaboration,remote,global',
  'ats-resume-international-candidates':           'resume,computer,office,hiring',
  'remote-job-uk-international':                   'london,uk,remote,work',
  'how-to-get-remote-job-usa-international':       'newyork,usa,remote,work',
  'how-to-get-remote-job-france-international':    'paris,eiffel,france,work',
  'remote-job-salary-by-country':                  'salary,money,international,remote',
  'how-to-find-remote-job-from-vietnam-2026':      'vietnam,hanoi,remote,work,laptop',
  'trouver-emploi-remote-depuis-etranger':         'remote,work,laptop,international,desk',
  'cross-border-remote-jobs-complete-guide':       'globe,world,remote,collaboration,laptop',
  'travailler-distance-entreprise-etrangere':      'contract,international,payment,remote,work',
  'best-remote-jobs-french-speakers-2026':         'france,bilingual,remote,work,laptop',
  'meilleurs-emplois-remote-francophones-2026':    'africa,francophone,remote,work,laptop',
  'international-jobs-without-relocating':         'remote,work,home,laptop,international',
  'postuler-emploi-international-sans-demenager':  'remote,work,laptop,europe,application',
  'remote-jobs-africa-global-companies':           'africa,remote,work,laptop,global',
  'emploi-remote-afrique-entreprises-mondiales':   'africa,remote,work,francophone,laptop',
  'visa-friendly-remote-jobs-employers-accept':    'visa,passport,remote,work,globe',
  'emploi-remote-visa-employeurs-acceptent':       'visa,europe,remote,work,contract',
  'how-ai-job-matching-works':                     'AI,matching,algorithm,laptop,technology',
  'matching-ia-emploi-comment-ca-marche':          'AI,matching,laptop,resume,technology',
  'remote-job-interview-prep-international-candidate': 'interview,remote,video,laptop,global',
  'preparer-entretien-emploi-remote-international':        'interview,remote,video,laptop,france',
  'hire-remote-talent-globally-without-local-entity':      'hiring,global,remote,team,employer',
  'recruter-talents-remote-monde-entier':                  'recrutement,remote,global,talent,équipe',
  'skill-gap-analysis-remote-jobs-guide':                  'skills,gap,analysis,remote,jobs',
  'analyse-competences-avant-postuler':                    'competences,gap,emploi,profil,remote',
  'linkedin-profile-optimization-international-jobs':      'linkedin,profile,remote,jobs,international',
  'optimiser-profil-linkedin-emploi-international':        'linkedin,profil,emploi,international,remote',
  'state-of-cross-border-remote-work-2026':                'remote,work,global,trends,2026',
  'teletravail-international-2026-etat-des-lieux':         'teletravail,international,afrique,2026,remote',
}

/** Returns heroImage if set, otherwise a keyword-based Unsplash URL */
export function getPostHeroImage(post: BlogPost): string {
  if (post.heroImage) return post.heroImage
  const kw = SLUG_KEYWORDS[post.slug] ?? 'remote,work,laptop,office'
  return `https://source.unsplash.com/1200x400/?${kw}`
}

/** Thumbnail variant (smaller crop) */
export function getPostThumbnail(post: BlogPost): string {
  if (post.heroImage) return post.heroImage
  const kw = SLUG_KEYWORDS[post.slug] ?? 'remote,work,laptop,office'
  return `https://source.unsplash.com/400x280/?${kw}`
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
}
