export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  date: string
  readingTime: number
  category: string
  categoryColor: string
  heroImage?: string    // absolute URL — overrides auto-generated Unsplash image
  heroImageAlt?: string
  ctaHref?: string
  ctaText?: string
  ctaSubtext?: string
  relatedPages?: { label: string; href: string }[]
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug:          'how-to-get-remote-job-france-international',
    heroImage:     '/images/blog/hero-international-laptop.jpg',
    heroImageAlt:  'Laptop with globe — international remote job search',
    title:         'How to Get a Remote Job in France as an International Candidate (2026)',
    excerpt:       'France tech is international — but only in certain sectors and at certain company stages. Learn the legal structures, CV format, lettre de motivation rules, and which platforms French companies actually use to hire globally.',
    date:          '2026-08-28',
    readingTime:   9,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-france',
    ctaText:       'Browse French remote jobs →',
    ctaSubtext:    'Roles at French tech companies genuinely open to international candidates.',
    relatedPages: [
      { label: '🇫🇷 Remote Jobs in France',              href: '/remote-jobs-france' },
      { label: '📄 Resume Format by Country',            href: '/blog/resume-format-by-country' },
      { label: '🌍 10 Skills for International Hire',    href: '/blog/cross-border-remote-job-skills' },
    ],
  },
  {
    slug:          'remote-job-salary-by-country',
    heroImage:     '/images/blog/hero-salary-by-country.jpg',
    heroImageAlt:  'World map showing remote job salary ranges by country',
    title:         'Remote Job Salaries by Country: What International Candidates Can Realistically Expect (2026)',
    excerpt:       'Why the $150K posted salary is not your salary as a contractor, how to benchmark correctly across US, UK, Germany, France and Canada, and the red flags that signal a company is underpaying international hires.',
    date:          '2026-08-26',
    readingTime:   9,
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Find roles with transparent pay ranges →',
    ctaSubtext:    'JobConnect AI surfaces salary info and contractor vs employee status on every listing.',
    relatedPages: [
      { label: '🇺🇸 US Remote Jobs for Internationals',  href: '/blog/how-to-get-remote-job-usa-international' },
      { label: '🌍 10 Skills for International Hire',    href: '/blog/cross-border-remote-job-skills' },
      { label: '🎯 ATS Optimization Guide',              href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'how-to-get-remote-job-in-germany-as-foreigner',
    heroImage:     '/images/blog/hero-germany.jpg',
    heroImageAlt:  'Map of Europe with Germany highlighted and German flag',
    title:         'How to Get a Remote Job in Germany as a Foreign National (2026 Guide)',
    excerpt:       'Everything you need to know about the Lebenslauf format, professional photos, cover letters, and which platforms actually hire internationally.',
    date:          '2026-08-15',
    readingTime:   8,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-germany',
    ctaText:       'Browse German remote jobs →',
    ctaSubtext:    'Filter for roles genuinely open to international candidates.',
    relatedPages: [
      { label: '🇩🇪 Remote Jobs in Germany',        href: '/remote-jobs-germany' },
      { label: '📄 Resume Format by Country',        href: '/blog/resume-format-by-country' },
    ],
  },
  {
    slug:          'resume-format-by-country',
    heroImage:     '/images/blog/hero-laptop-world.jpg',
    heroImageAlt:  'Laptop displaying a world map at a remote work desk',
    title:         'Resume Format by Country: US vs UK vs Germany vs France vs Canada',
    excerpt:       'A practical comparison of what hiring managers in 5 countries expect — photos, length, tone, personal information, and the differences that trip up international applicants.',
    date:          '2026-08-10',
    readingTime:   6,
    category:      'Resume Tips',
    categoryColor: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
    ctaHref:       '/ai-tools/resume-builder',
    ctaText:       'Build your country-specific resume →',
    ctaSubtext:    'AI resume builder that adapts to US, UK, German, French, and Canadian formats.',
    relatedPages: [
      { label: '🇩🇪 Remote Jobs in Germany', href: '/remote-jobs-germany' },
      { label: '🇫🇷 Remote Jobs in France',  href: '/remote-jobs-france' },
      { label: '🇬🇧 Remote Jobs in the UK',  href: '/remote-jobs-uk' },
    ],
  },
  {
    slug:          'how-to-spot-fake-remote-jobs',
    heroImage:     '/images/blog/hero-remote-desk.jpg',
    heroImageAlt:  'Laptop and coffee on a desk — remote work setup',
    title:         "How to Tell if a Remote Job Actually Hires Internationally (and Which Don't)",
    excerpt:       'The exact phrases to look for, the red flags that cost you hours of wasted applications, and how our Remote-Friendly Detector automates this for you.',
    date:          '2026-08-05',
    readingTime:   5,
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Search pre-filtered remote jobs →',
    ctaSubtext:    'Every listing run through our Remote-Friendly Detector before you see it.',
    relatedPages: [
      { label: '🎯 ATS Tips for International Candidates', href: '/blog/ats-resume-international-candidates' },
      { label: '🌍 10 Skills That Make You Hireable',      href: '/blog/cross-border-remote-job-skills' },
    ],
  },
  {
    slug:          'how-to-get-remote-job-canada-international',
    heroImage:     '/images/blog/hero-canada.jpg',
    heroImageAlt:  'Map of North America with Canada highlighted and Canadian flag',
    title:         'How to Get a Remote Job in Canada as an International Candidate (2026)',
    excerpt:       "Canada actively recruits global tech talent — but the rules differ from the US. Here's everything you need to know about work permits, bilingual advantage, and the Canadian application style.",
    date:          '2026-08-22',
    readingTime:   8,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-canada',
    ctaText:       'Browse Canadian remote jobs →',
    ctaSubtext:    'Roles filtered for international candidates — contractor and employee.',
    relatedPages: [
      { label: '🇨🇦 Remote Jobs in Canada',   href: '/remote-jobs-canada' },
      { label: '🇺🇸 Remote Jobs in the USA',   href: '/remote-jobs-usa' },
      { label: '📄 Resume Format by Country',  href: '/blog/resume-format-by-country' },
    ],
  },
  {
    slug:          'remote-work-france-foreigner',
    heroImage:     '/images/blog/hero-france.jpg',
    heroImageAlt:  'Map of Europe with France highlighted and French flag',
    title:         'Working Remotely for a French Company as a Foreigner: What You Need to Know',
    excerpt:       'French professional culture, the CV format with no photo, the art of the lettre de motivation, and the platforms where international candidates actually find French remote roles.',
    date:          '2026-08-20',
    readingTime:   7,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-france',
    ctaText:       'Browse French remote jobs →',
    ctaSubtext:    'French companies that genuinely hire international remote workers.',
    relatedPages: [
      { label: '🇫🇷 Remote Jobs in France',         href: '/remote-jobs-france' },
      { label: '📄 Resume Format by Country',        href: '/blog/resume-format-by-country' },
    ],
  },
  {
    slug:          'cross-border-remote-job-skills',
    heroImage:     '/images/blog/hero-cross-border-skills.jpg',
    heroImageAlt:  'Globe with connection lines — cross-border remote skills',
    title:         'The 10 Skills That Make You Hireable Internationally (For Remote Jobs)',
    excerpt:       'Technical skills get you through the door. These 10 cross-border skills determine whether a company in Germany, Canada, or the UK actually hires you over a local candidate.',
    date:          '2026-08-18',
    readingTime:   6,
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Find remote jobs matching your skills →',
    ctaSubtext:    'AI-matched remote roles for international candidates.',
    relatedPages: [
      { label: '🎯 ATS Optimization Guide',        href: '/blog/ats-resume-international-candidates' },
      { label: '🌍 Remote-Friendly Job Checklist', href: '/blog/how-to-spot-fake-remote-jobs' },
    ],
  },
  {
    slug:          'ats-resume-international-candidates',
    heroImage:     '/images/blog/hero-ats-resume.jpg',
    heroImageAlt:  'ATS resume scanning icon with orbit rings',
    title:         'ATS Optimization for International Candidates: Why Your Resume Gets Rejected',
    excerpt:       'Most international candidates are filtered out before a human ever reads their resume. Here is exactly how ATS systems work, why international resumes fail, and how to fix yours.',
    date:          '2026-08-16',
    readingTime:   6,
    category:      'Resume Tips',
    categoryColor: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
    ctaHref:       '/ai-tools/resume-builder',
    ctaText:       'Build your ATS-optimized resume →',
    ctaSubtext:    'Our AI resume builder formats your CV to pass international ATS filters.',
    relatedPages: [
      { label: '📄 Resume Format by Country',       href: '/blog/resume-format-by-country' },
      { label: '🌍 10 Skills for International Hire', href: '/blog/cross-border-remote-job-skills' },
    ],
  },
  {
    slug:          'how-to-get-remote-job-usa-international',
    heroImage:     '/images/blog/hero-usa.jpg',
    heroImageAlt:  'Map of North America with USA highlighted and American flag',
    title:         'How to Get a Remote Job in the USA as an International Candidate (2026)',
    excerpt:       'The US is the largest remote job market — but most listings exclude non-US candidates by default. Learn W-2 vs 1099 vs Corp-to-Corp, how to detect genuinely international-open roles, and how to position yourself to win.',
    date:          '2026-08-24',
    readingTime:   10,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-usa',
    ctaText:       'Browse US remote jobs open to internationals →',
    ctaSubtext:    'Pre-filtered for C2C, EOR-supported, and global-remote US roles.',
    relatedPages: [
      { label: '🇺🇸 Remote Jobs in the USA',              href: '/remote-jobs-usa' },
      { label: '🎯 ATS Optimization for Internationals',  href: '/blog/ats-resume-international-candidates' },
      { label: '🔍 Spot Roles That Actually Hire Globally', href: '/blog/how-to-spot-fake-remote-jobs' },
    ],
  },
  {
    slug:          'remote-job-uk-international',
    heroImage:     '/images/blog/hero-uk.jpg',
    heroImageAlt:  'Map of Europe with UK highlighted and British flag',
    title:         'How to Land a Remote Job in the UK as a Non-UK Resident (2026)',
    excerpt:       "Post-Brexit, right-to-work rules, British CV format, and which UK sectors genuinely hire international remote workers — everything you need to run a smart UK job search.",
    date:          '2026-08-14',
    readingTime:   8,
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/remote-jobs-uk',
    ctaText:       'Browse UK remote jobs →',
    ctaSubtext:    'UK companies filtered for international candidates — with right-to-work clarity.',
    relatedPages: [
      { label: '🇬🇧 Remote Jobs in the UK',         href: '/remote-jobs-uk' },
      { label: '📄 Resume Format by Country',        href: '/blog/resume-format-by-country' },
      { label: '🎯 ATS Optimization Guide',          href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'how-to-find-remote-job-from-vietnam-2026',
    title:         'How to Find a Remote Job From Vietnam in 2026: The Complete Strategy',
    excerpt:       "Vietnam's tech workforce is internationally competitive — but visibility and positioning are the real challenges. A complete guide to platforms, timezone advantage, sectors, CV formatting, and getting paid across borders.",
    date:          '2026-09-02',
    readingTime:   9,
    heroImage:     '/images/blog/remote-job-vietnam.jpg',
    heroImageAlt:  'Laptop with Ho Chi Minh City skyline — remote work from Vietnam',
    category:      'Country Guides',
    categoryColor: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    ctaHref:       '/jobs',
    ctaText:       'Browse remote jobs open to Vietnam →',
    ctaSubtext:    'Verified international remote listings with explicit location filtering.',
    relatedPages: [
      { label: '🌍 Cross-Border Remote Jobs Guide',       href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '📄 Resume Format by Country',             href: '/blog/resume-format-by-country' },
      { label: '🎯 ATS Optimization for Internationals',  href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'trouver-emploi-remote-depuis-etranger',
    title:         "Trouver un Emploi Remote depuis l'Étranger : Guide Pratique Multi-Marchés (2026)",
    excerpt:       "Comment trouver des offres réellement ouvertes aux candidats étrangers, choisir le bon statut contractuel, rédiger une candidature qui rassure les recruteurs, et recevoir son salaire depuis l'étranger.",
    date:          '2026-09-04',
    readingTime:   9,
    heroImage:     '/images/blog/emploi-remote-etranger.jpg',
    heroImageAlt:  'Professionnelle travaillant sur ordinateur portable avec carte du monde en arrière-plan',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Parcourir les offres remote internationales →',
    ctaSubtext:    "Offres vérifiées avec filtrage géographique explicite pour les candidats basés à l'étranger.",
    relatedPages: [
      { label: '🌍 Guide complet du remote transfrontalier',     href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: "⚖️ Travailler à distance pour l'étranger",      href: '/blog/travailler-distance-entreprise-etrangere' },
      { label: '📄 Postuler sans déménager',                    href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'cross-border-remote-jobs-complete-guide',
    title:         'Cross-Border Remote Jobs: The Complete A-to-Z Guide (Find, Apply, Negotiate, Sign)',
    excerpt:       'Every step of landing an international remote job without relocating — from finding genuinely open listings to understanding what you are signing. The process is a skill, and this guide teaches it.',
    date:          '2026-09-08',
    readingTime:   11,
    heroImage:     '/images/blog/cross-border-remote-guide.jpg',
    heroImageAlt:  'World map with coloured country flags connected by glowing lines — cross-border remote work',
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Find your next cross-border role →',
    ctaSubtext:    'International remote listings verified for genuine location openness.',
    relatedPages: [
      { label: '🔍 Spot Roles That Actually Hire Globally',  href: '/blog/how-to-spot-fake-remote-jobs' },
      { label: '🌍 10 Skills for International Hire',        href: '/blog/cross-border-remote-job-skills' },
      { label: '🎯 ATS Optimization Guide',                  href: '/blog/ats-resume-international-candidates' },
    ],
  },
  {
    slug:          'travailler-distance-entreprise-etrangere',
    title:         'Travailler à Distance pour une Entreprise Étrangère : Contrats, Paiement, Fiscalité (2026)',
    excerpt:       "Tout ce qu'il faut savoir sur les structures contractuelles internationales, la réception de paiements étrangers via Wise ou EOR, la fiscalité des revenus étrangers, et la protection sociale quand l'employeur est à l'étranger.",
    date:          '2026-09-10',
    readingTime:   10,
    heroImage:     '/images/blog/travailler-entreprise-etrangere.jpg',
    heroImageAlt:  'Main signant un contrat numérique avec devises internationales euro livre yen en arrière-plan',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Trouver une offre remote internationale →',
    ctaSubtext:    "Offres d'entreprises déjà équipées pour recruter à l'international.",
    relatedPages: [
      { label: "🌍 Trouver un emploi remote depuis l'étranger",  href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '📄 Postuler sans déménager',                     href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'best-remote-jobs-french-speakers-2026',
    title:         'Best Remote Jobs for French Speakers in 2026: Sectors, Companies, and Salaries',
    excerpt:       'French-English bilingualism is a premium qualification in international remote hiring. A sector-by-sector breakdown of where demand is highest, which companies recruit bilingual talent most actively, and how to position the advantage correctly.',
    date:          '2026-09-12',
    readingTime:   9,
    heroImage:     '/images/blog/remote-jobs-french-speakers.jpg',
    heroImageAlt:  'France and Canada flags connected to Africa by glowing arcs — Francophone remote job market',
    category:      'Career Advice',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Browse remote jobs requiring French →',
    ctaSubtext:    'Filter for bilingual FR/EN roles at international companies.',
    relatedPages: [
      { label: '🇫🇷 Remote Jobs in France',                        href: '/remote-jobs-france' },
      { label: '🇨🇦 Remote Jobs in Canada',                        href: '/remote-jobs-canada' },
      { label: '🌍 Meilleurs emplois remote francophones 2026',    href: '/blog/meilleurs-emplois-remote-francophones-2026' },
    ],
  },
  {
    slug:          'meilleurs-emplois-remote-francophones-2026',
    title:         'Meilleurs Emplois Remote pour les Francophones en 2026 : Secteurs, Salaires et Plateformes',
    excerpt:       "Guide complet pour les professionnels francophones d'Afrique subsaharienne, d'Haïti et des DOM-TOM : secteurs porteurs, niveaux de rémunération réalistes, plateformes efficaces et stratégie de candidature.",
    date:          '2026-09-16',
    readingTime:   10,
    heroImage:     '/images/blog/emplois-remote-francophones.jpg',
    heroImageAlt:  "Carte numérique montrant l'Afrique connectée à l'Europe et aux Amériques — emploi remote francophone",
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Parcourir les offres remote francophones →',
    ctaSubtext:    'Offres avec filtrage linguistique pour les candidats francophones.',
    relatedPages: [
      { label: "🌍 Trouver un emploi remote depuis l'étranger",      href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '🌐 Best remote jobs for French speakers',             href: '/blog/best-remote-jobs-french-speakers-2026' },
      { label: "⚖️ Travailler à distance pour une entreprise étrangère", href: '/blog/travailler-distance-entreprise-etrangere' },
    ],
  },
  {
    slug:          'international-jobs-without-relocating',
    title:         "International Jobs Without Relocating: How to Win Remote Arrangements Employers Don't Advertise",
    excerpt:       "Most 'must be on-site' postings are negotiable. How to screen job listings before applying, make the case for full remote during the process, and negotiate location at the moment of maximum leverage — without burning the relationship.",
    date:          '2026-09-18',
    readingTime:   9,
    heroImage:     '/images/blog/international-jobs-no-relocation.jpg',
    heroImageAlt:  'Person working from home with world map and location pins — international jobs without relocating',
    category:      'Job Search',
    categoryColor: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    ctaHref:       '/jobs',
    ctaText:       'Find remote-friendly international roles →',
    ctaSubtext:    "Remote-Friendly Detector surfaces companies already distributed — even when postings don't say so.",
    relatedPages: [
      { label: '🔍 Spot Roles That Actually Hire Globally',  href: '/blog/how-to-spot-fake-remote-jobs' },
      { label: '🌍 Cross-Border Remote Jobs Guide',          href: '/blog/cross-border-remote-jobs-complete-guide' },
      { label: '📄 Postuler sans déménager (FR)',            href: '/blog/postuler-emploi-international-sans-demenager' },
    ],
  },
  {
    slug:          'postuler-emploi-international-sans-demenager',
    title:         'Postuler à un Emploi International Sans Déménager : Candidature Remote-First et Négociation (2026)',
    excerpt:       "Comment lire une offre 'sur site' comme un recruteur, présenter une candidature remote-first sans perdre en crédibilité, et négocier un arrangement de télétravail au moment de l'offre avec les arguments qui convainquent les recruteurs européens.",
    date:          '2026-09-22',
    readingTime:   10,
    heroImage:     '/images/blog/postuler-international-sans-demenager.jpg',
    heroImageAlt:  'Maison connectée au globe numérique — postuler à un emploi international sans déménager',
    category:      'Conseils Carrière',
    categoryColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    ctaHref:       '/jobs',
    ctaText:       'Trouver une offre internationale négociable →',
    ctaSubtext:    "Offres avec signaux d'ouverture au travail distribué affichés sur chaque fiche.",
    relatedPages: [
      { label: "🌍 Trouver un emploi remote depuis l'étranger",  href: '/blog/trouver-emploi-remote-depuis-etranger' },
      { label: '🌐 International jobs without relocating (EN)',   href: '/blog/international-jobs-without-relocating' },
      { label: "⚖️ Travailler à distance pour l'étranger",       href: '/blog/travailler-distance-entreprise-etrangere' },
    ],
  },
]

export function getPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug)
}

// Slug → Unsplash search keywords for auto-generated images
const SLUG_KEYWORDS: Record<string, string> = {
  'how-to-get-remote-job-in-germany-as-foreigner': 'germany,berlin,remote,work',
  'resume-format-by-country':                      'resume,laptop,desk,professional',
  'how-to-spot-fake-remote-jobs':                  'job,search,laptop,coffee,focus',
  'how-to-get-remote-job-canada-international':    'canada,toronto,remote,work',
  'remote-work-france-foreigner':                  'paris,france,remote,work',
  'cross-border-remote-job-skills':                'teamwork,collaboration,remote,global',
  'ats-resume-international-candidates':           'resume,computer,office,hiring',
  'remote-job-uk-international':                   'london,uk,remote,work',
  'how-to-get-remote-job-usa-international':       'newyork,usa,remote,work',
  'how-to-get-remote-job-france-international':    'paris,eiffel,france,work',
  'remote-job-salary-by-country':                  'salary,money,international,remote',
  'how-to-find-remote-job-from-vietnam-2026':      'vietnam,hanoi,remote,work,laptop',
  'trouver-emploi-remote-depuis-etranger':         'remote,work,laptop,international,desk',
  'cross-border-remote-jobs-complete-guide':       'globe,world,remote,collaboration,laptop',
  'travailler-distance-entreprise-etrangere':      'contract,international,payment,remote,work',
  'best-remote-jobs-french-speakers-2026':         'france,bilingual,remote,work,laptop',
  'meilleurs-emplois-remote-francophones-2026':    'africa,francophone,remote,work,laptop',
  'international-jobs-without-relocating':         'remote,work,home,laptop,international',
  'postuler-emploi-international-sans-demenager':  'remote,work,laptop,europe,application',
}

/** Returns heroImage if set, otherwise a keyword-based Unsplash URL */
export function getPostHeroImage(post: BlogPost): string {
  if (post.heroImage) return post.heroImage
  const kw = SLUG_KEYWORDS[post.slug] ?? 'remote,work,laptop,office'
  return `https://source.unsplash.com/1200x400/?${kw}`
}

/** Thumbnail variant (smaller crop) */
export function getPostThumbnail(post: BlogPost): string {
  if (post.heroImage) return post.heroImage
  const kw = SLUG_KEYWORDS[post.slug] ?? 'remote,work,laptop,office'
  return `https://source.unsplash.com/400x280/?${kw}`
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
}
