import json

TRANSLATIONS = {
  "en": {
    "greeting1": "👋 Hi there! I'm the JobConnect AI assistant. How can I help you today?",
    "greeting2": "Choose a topic below or type your question.",
    "online": "Online",
    "repliesInstantly": "Typically replies instantly",
    "poweredBy": "Powered by JobConnect AI",
    "minimize": "Minimize chat",
    "expand": "Expand view",
    "collapse": "Collapse view",
    "download": "Download transcript",
    "newConversation": "New conversation",
    "transcriptTitle": "JobConnect AI - Chat Transcript",
    "transcriptDate": "Date",
    "transcriptYou": "You",
    "expandChat": "Maximize",
    "reduceChat": "Restore",
    "themeGettingStarted": "Getting Started",
    "themeAiTools": "AI Tools",
    "themeInternational": "International",
    "themeBilling": "Billing & Account",
    "themeSecurity": "Security & Support",
    "q_whatIs": "What is JobConnect AI?",
    "a_whatIs": "JobConnect AI is a career copilot built for international professionals seeking remote jobs across borders. AI-powered tools + a curated remote job board — all in one place.",
    "q_whoFor": "Who is JobConnect AI for?",
    "a_whoFor": "JobConnect AI is built for ambitious professionals who refuse to let geography limit their career. Whether you're a developer in Vietnam targeting a Berlin startup, or a finance professional in Southeast Asia eyeing a Canadian firm — if you're chasing a remote career that crosses borders, this platform was built for you.",
    "q_different": "What makes JobConnect AI different from LinkedIn or Indeed?",
    "a_different": "LinkedIn and Indeed are built country by country. International professionals fall through the cracks. JobConnect AI is built from the ground up for the cross-border job seeker — every tool, every feature designed for someone applying across borders.",
    "q_free": "Is it free?",
    "a_free": "Yes! Browsing jobs and applying is free forever. Premium AI tools (Resume Builder, Cover Letter, Interview Prep and more) start at $19/month.",
    "q_trial": "Do you offer a free trial?",
    "a_trial": "Our free plan gives you job browsing, applications, and your candidate dashboard — indefinitely. Upgrade to Premium when you're ready. No trial period needed.",
    "q_premium": "What does Premium include?",
    "a_premium": "Unlimited AI resumes & cover letters, ATS scoring, Interview Prep, Skill Gap Analysis, Career Coach, and country-specific formatting for US, UK, Canada, Germany and France — powered by GPT-4o.",
    "q_resumeBuilder": "How does the AI Resume Builder work?",
    "a_resumeBuilder": "Tell us your target role, experience, and skills. Our AI generates an ATS-optimized resume tailored to the specific country you're targeting. A resume for Germany looks very different from one for the US — we handle those differences automatically.",
    "q_detector": "What is the Remote-Friendly Detector?",
    "a_detector": "Our Remote-Friendly Detector analyzes every job listing to determine whether it genuinely welcomes international candidates — displaying a Likely / Unclear / Unlikely badge so you never waste time on the wrong applications.",
    "q_skillGap": "How does the Skill Gap Analysis work?",
    "a_skillGap": "Enter your target role and country. Our AI identifies your missing skills, relevant certifications recognized in that market, language expectations, and cultural norms. Market-specific intelligence, not generic advice.",
    "q_coverLetter": "What is the AI Cover Letter Generator?",
    "a_coverLetter": "It creates personalized cover letters tailored to the company, role, and target country's professional tone. A cover letter for a German company sounds very different from one for a British firm. Our AI knows the difference.",
    "q_interviewPrep": "What is Interview Prep?",
    "a_interviewPrep": "Your personal AI interview coach. Get realistic interview questions — behavioral, technical, situational — with instant detailed feedback on your answers. Available 24/7, from anywhere.",
    "q_careerCoach": "What is the Career Coach?",
    "a_careerCoach": "A comprehensive analysis of your professional profile: ATS score, skill gaps, salary benchmarks, and a personalized roadmap to your next career milestone. A senior career advisor available 24/7.",
    "q_copilot": "How does the Copilot work?",
    "a_copilot": "Just type what you need in plain language — \"Improve my resume for Amazon\" or \"Find remote jobs in France.\" Our AI Copilot understands your intent and takes you directly to the right tool, pre-filled. No menus, no friction.",
    "q_countries": "What countries are supported?",
    "a_countries": "Our AI tools are fully optimized for five major job markets: United States, United Kingdom, Canada, Germany, and France. Support for additional markets is coming soon.",
    "q_anywhere": "Can I apply from anywhere?",
    "a_anywhere": "Absolutely. JobConnect AI is built for professionals based anywhere in the world targeting remote roles internationally. Your location is not a barrier.",
    "q_fromOutside": "Can I apply to jobs from outside my country?",
    "a_fromOutside": "Absolutely. Whether you're based in Asia, Africa, Latin America, or Eastern Europe — you can browse, apply, and land remote roles with top companies worldwide. Your location is not a barrier.",
    "q_billing": "How does billing work?",
    "a_billing": "Premium is billed monthly at $19/month. Cancel anytime — no contracts, no cancellation fees. If you cancel, you keep access until the end of your billing period.",
    "q_cancel": "How do I cancel my subscription?",
    "a_cancel": "Go to your account settings and cancel in one click. No phone calls, no forms. You keep full Premium access until the end of your billing cycle.",
    "q_secure": "Is my data secure?",
    "a_secure": "Your data is protected by enterprise-grade security with Row Level Security. Your information is only accessible by you — we never sell your data or share it with third parties.",
    "q_support": "How do I contact support?",
    "a_support": "Email us at contact@jobconnect-ai.com — we typically respond within 24 hours."
  },
  "fr": {
    "greeting1": "👋 Bonjour ! Je suis l'assistant JobConnect AI. Comment puis-je vous aider aujourd'hui ?",
    "greeting2": "Choisissez un sujet ci-dessous ou posez votre question.",
    "online": "En ligne",
    "repliesInstantly": "Répond généralement instantanément",
    "poweredBy": "Propulsé par JobConnect AI",
    "minimize": "Réduire le chat",
    "expand": "Agrandir la vue",
    "collapse": "Réduire la vue",
    "download": "Télécharger la transcription",
    "newConversation": "Nouvelle conversation",
    "transcriptTitle": "JobConnect AI - Transcription du chat",
    "transcriptDate": "Date",
    "transcriptYou": "Vous",
    "expandChat": "Agrandir",
    "reduceChat": "Restaurer",
    "themeGettingStarted": "Pour commencer",
    "themeAiTools": "Outils IA",
    "themeInternational": "International",
    "themeBilling": "Facturation & Compte",
    "themeSecurity": "Sécurité & Support",
    "q_whatIs": "Qu'est-ce que JobConnect AI ?",
    "a_whatIs": "JobConnect AI est un copilote de carrière pour les professionnels internationaux à la recherche d'emplois à distance au-delà des frontières. Outils IA + tableau d'offres à distance — le tout en un seul endroit.",
    "q_whoFor": "Pour qui est fait JobConnect AI ?",
    "a_whoFor": "Pour les professionnels ambitieux qui refusent de laisser la géographie limiter leur carrière. Développeur au Vietnam visant une startup berlinoise ou financier en Asie visant une entreprise canadienne — cette plateforme a été créée pour vous.",
    "q_different": "En quoi JobConnect AI se distingue-t-il de LinkedIn ou Indeed ?",
    "a_different": "LinkedIn et Indeed sont construits pays par pays. JobConnect AI est construit de zéro pour le chercheur d'emploi transfrontalier.",
    "q_free": "Est-ce gratuit ?",
    "a_free": "Oui ! La navigation et les candidatures sont gratuites pour toujours. Les outils IA Premium débutent à 19 $/mois.",
    "q_trial": "Proposez-vous un essai gratuit ?",
    "a_trial": "Notre plan gratuit vous donne accès à la navigation, aux candidatures et à votre tableau de bord — indéfiniment.",
    "q_premium": "Qu'inclut le Premium ?",
    "a_premium": "CV et lettres de motivation IA illimités, score ATS, Préparation aux entretiens, Analyse des lacunes, Coach Carrière, et mise en forme pour USA, UK, Canada, Allemagne et France — propulsé par GPT-4o.",
    "q_resumeBuilder": "Comment fonctionne le Générateur de CV IA ?",
    "a_resumeBuilder": "Indiquez votre poste cible, votre expérience et vos compétences. Notre IA génère un CV optimisé ATS adapté au pays cible. Un CV pour l'Allemagne est très différent d'un CV pour les USA.",
    "q_detector": "Qu'est-ce que le Détecteur Remote-Friendly ?",
    "a_detector": "Analyse chaque offre et affiche un badge Probable / Incertain / Peu probable pour ne pas perdre de temps sur les mauvaises candidatures.",
    "q_skillGap": "Comment fonctionne l'Analyse des lacunes de compétences ?",
    "a_skillGap": "Entrez votre poste cible et votre pays. Notre IA identifie vos compétences manquantes, les certifications reconnues, les attentes linguistiques et les normes culturelles.",
    "q_coverLetter": "Qu'est-ce que le Générateur de lettres de motivation IA ?",
    "a_coverLetter": "Crée des lettres de motivation personnalisées adaptées au ton professionnel du pays cible. Notre IA connaît la différence entre une lettre pour une entreprise allemande et britannique.",
    "q_interviewPrep": "Qu'est-ce que la Préparation aux entretiens ?",
    "a_interviewPrep": "Votre coach d'entretien IA personnel. Questions réalistes — comportementales, techniques, situationnelles — avec retour détaillé instantané. Disponible 24h/24.",
    "q_careerCoach": "Qu'est-ce que le Coach Carrière ?",
    "a_careerCoach": "Analyse complète de votre profil : score ATS, lacunes, benchmarks salariaux, et feuille de route personnalisée. Conseiller career senior disponible 24h/24.",
    "q_copilot": "Comment fonctionne le Copilot ?",
    "a_copilot": "Tapez ce dont vous avez besoin en langage naturel. Le Copilot IA vous amène directement au bon outil, pré-rempli.",
    "q_countries": "Quels pays sont pris en charge ?",
    "a_countries": "Optimisés pour cinq marchés : États-Unis, Royaume-Uni, Canada, Allemagne et France. D'autres marchés arrivent bientôt.",
    "q_anywhere": "Puis-je postuler depuis n'importe où ?",
    "a_anywhere": "Absolument. Votre emplacement n'est pas un obstacle.",
    "q_fromOutside": "Puis-je postuler depuis l'extérieur de mon pays ?",
    "a_fromOutside": "Absolument. Depuis l'Asie, l'Afrique, l'Amérique latine ou l'Europe de l'Est — vous pouvez décrocher des postes à distance dans les meilleures entreprises mondiales.",
    "q_billing": "Comment fonctionne la facturation ?",
    "a_billing": "19 $/mois. Annulez à tout moment — sans contrats, sans frais d'annulation.",
    "q_cancel": "Comment annuler mon abonnement ?",
    "a_cancel": "Un clic dans les paramètres de votre compte. Vous conservez l'accès Premium jusqu'à la fin de votre cycle.",
    "q_secure": "Mes données sont-elles sécurisées ?",
    "a_secure": "Protégées par une sécurité de niveau entreprise. Vos informations ne sont accessibles que par vous — nous ne les vendons ni partageons jamais.",
    "q_support": "Comment contacter le support ?",
    "a_support": "Envoyez un e-mail à contact@jobconnect-ai.com — nous répondons dans les 24 heures."
  },
  "de": {
    "greeting1": "👋 Hallo! Ich bin der JobConnect AI-Assistent. Wie kann ich Ihnen heute helfen?",
    "greeting2": "Wählen Sie ein Thema unten oder stellen Sie Ihre Frage.",
    "online": "Online",
    "repliesInstantly": "Antwortet in der Regel sofort",
    "poweredBy": "Unterstützt von JobConnect AI",
    "minimize": "Chat minimieren",
    "expand": "Ansicht erweitern",
    "collapse": "Ansicht reduzieren",
    "download": "Transkript herunterladen",
    "newConversation": "Neue Unterhaltung",
    "transcriptTitle": "JobConnect AI - Chat-Transkript",
    "transcriptDate": "Datum",
    "transcriptYou": "Sie",
    "expandChat": "Maximieren",
    "reduceChat": "Wiederherstellen",
    "themeGettingStarted": "Erste Schritte",
    "themeAiTools": "KI-Tools",
    "themeInternational": "International",
    "themeBilling": "Abrechnung & Konto",
    "themeSecurity": "Sicherheit & Support",
    "q_whatIs": "Was ist JobConnect AI?",
    "a_whatIs": "JobConnect AI ist ein Karriere-Copilot für internationale Fachkräfte, die Remote-Jobs grenzübergreifend suchen. KI-gestützte Tools + eine kuratierte Remote-Jobbörse — alles an einem Ort.",
    "q_whoFor": "Für wen ist JobConnect AI?",
    "a_whoFor": "Für ehrgeizige Fachkräfte, die sich nicht von der Geographie einschränken lassen wollen. Ob Entwickler in Vietnam mit Ziel Berliner Start-up oder Finanzfachmann in Südostasien — diese Plattform wurde für Sie gebaut.",
    "q_different": "Was unterscheidet JobConnect AI von LinkedIn oder Indeed?",
    "a_different": "LinkedIn und Indeed sind länderspezifisch aufgebaut. JobConnect AI wurde von Grund auf für den grenzüberschreitenden Jobsuchenden entwickelt.",
    "q_free": "Ist es kostenlos?",
    "a_free": "Ja! Jobs durchsuchen und bewerben ist für immer kostenlos. Premium-KI-Tools beginnen bei 19 $/Monat.",
    "q_trial": "Gibt es eine kostenlose Testphase?",
    "a_trial": "Unser kostenloser Plan bietet Jobsuche, Bewerbungen und Ihr Kandidaten-Dashboard — unbefristet.",
    "q_premium": "Was beinhaltet Premium?",
    "a_premium": "Unbegrenzte KI-Lebensläufe & Anschreiben, ATS-Bewertung, Interviewvorbereitung, Kompetenzlückenanalyse, Karriere-Coach und länderspezifische Formatierung für USA, UK, Kanada, Deutschland und Frankreich — betrieben von GPT-4o.",
    "q_resumeBuilder": "Wie funktioniert der KI-Lebenslauf-Builder?",
    "a_resumeBuilder": "Teilen Sie uns Ihre Zielstelle, Erfahrung und Fähigkeiten mit. Unsere KI erstellt einen ATS-optimierten Lebenslauf für das Zielland. Ein Lebenslauf für Deutschland sieht ganz anders aus als einer für die USA.",
    "q_detector": "Was ist der Remote-Friendly-Detektor?",
    "a_detector": "Analysiert jedes Stellenangebot und zeigt ein Badge — Wahrscheinlich / Unklar / Unwahrscheinlich — damit Sie keine Zeit mit falschen Bewerbungen verschwenden.",
    "q_skillGap": "Wie funktioniert die Kompetenzlückenanalyse?",
    "a_skillGap": "Geben Sie Ihre Zielstelle und Ihr Land ein. Unsere KI identifiziert fehlende Fähigkeiten, relevante Zertifizierungen, Spracherwartungen und kulturelle Normen.",
    "q_coverLetter": "Was ist der KI-Anschreiben-Generator?",
    "a_coverLetter": "Erstellt personalisierte Anschreiben für den professionellen Ton des Ziellandes. Unsere KI kennt den Unterschied zwischen deutschen und britischen Unternehmen.",
    "q_interviewPrep": "Was ist die Interviewvorbereitung?",
    "a_interviewPrep": "Ihr persönlicher KI-Interviewcoach. Realistische Fragen mit sofortigem detailliertem Feedback. Rund um die Uhr verfügbar.",
    "q_careerCoach": "Was ist der Karriere-Coach?",
    "a_careerCoach": "Umfassende Analyse Ihres Berufsprofils: ATS-Score, Kompetenzlücken, Gehaltsbenchmarks und personalisierte Roadmap. Rund um die Uhr verfügbar.",
    "q_copilot": "Wie funktioniert der Copilot?",
    "a_copilot": "Tippen Sie in einfacher Sprache, was Sie brauchen. Der KI-Copilot führt Sie direkt zum richtigen, vorausgefüllten Tool.",
    "q_countries": "Welche Länder werden unterstützt?",
    "a_countries": "Für fünf Märkte optimiert: USA, Vereinigtes Königreich, Kanada, Deutschland und Frankreich. Weitere Märkte folgen.",
    "q_anywhere": "Kann ich von überall bewerben?",
    "a_anywhere": "Absolut. Ihr Standort ist keine Barriere.",
    "q_fromOutside": "Kann ich mich von außerhalb meines Landes bewerben?",
    "a_fromOutside": "Absolut. Ob in Asien, Afrika, Lateinamerika oder Osteuropa — Sie können Remote-Stellen bei Top-Unternehmen weltweit finden und landen.",
    "q_billing": "Wie funktioniert die Abrechnung?",
    "a_billing": "Premium wird monatlich mit 19 $/Monat berechnet. Jederzeit kündbar — keine Verträge, keine Stornogebühren.",
    "q_cancel": "Wie kündige ich mein Abonnement?",
    "a_cancel": "Gehen Sie zu Ihren Kontoeinstellungen und kündigen Sie mit einem Klick. Sie behalten Premium-Zugang bis Ende des Abrechnungszyklus.",
    "q_secure": "Sind meine Daten sicher?",
    "a_secure": "Durch Sicherheit auf Unternehmensebene geschützt. Nur Sie haben Zugriff — wir verkaufen oder teilen Ihre Daten niemals.",
    "q_support": "Wie kontaktiere ich den Support?",
    "a_support": "Senden Sie eine E-Mail an contact@jobconnect-ai.com — wir antworten in der Regel innerhalb von 24 Stunden."
  },
  "es": {
    "greeting1": "👋 ¡Hola! Soy el asistente de JobConnect AI. ¿Cómo puedo ayudarte hoy?",
    "greeting2": "Elige un tema a continuación o escribe tu pregunta.",
    "online": "En línea",
    "repliesInstantly": "Responde típicamente al instante",
    "poweredBy": "Desarrollado por JobConnect AI",
    "minimize": "Minimizar chat",
    "expand": "Ampliar vista",
    "collapse": "Reducir vista",
    "download": "Descargar transcripción",
    "newConversation": "Nueva conversación",
    "transcriptTitle": "JobConnect AI - Transcripción del chat",
    "transcriptDate": "Fecha",
    "transcriptYou": "Tú",
    "expandChat": "Maximizar",
    "reduceChat": "Restaurar",
    "themeGettingStarted": "Primeros pasos",
    "themeAiTools": "Herramientas de IA",
    "themeInternational": "Internacional",
    "themeBilling": "Facturación y Cuenta",
    "themeSecurity": "Seguridad y Soporte",
    "q_whatIs": "¿Qué es JobConnect AI?",
    "a_whatIs": "JobConnect AI es un copiloto profesional para internacionales que buscan trabajo remoto sin fronteras. Herramientas de IA + directorio de empleos remotos curado — todo en un lugar.",
    "q_whoFor": "¿Para quién es JobConnect AI?",
    "a_whoFor": "Para profesionales ambiciosos que no dejan que la geografía limite su carrera. Esta plataforma es para ti si buscas una carrera remota que cruce fronteras.",
    "q_different": "¿Qué diferencia a JobConnect AI de LinkedIn o Indeed?",
    "a_different": "LinkedIn e Indeed están construidos país por país. JobConnect AI fue diseñado desde cero para quien busca trabajo transfronterizo.",
    "q_free": "¿Es gratis?",
    "a_free": "¡Sí! Explorar empleos y aplicar es gratuito para siempre. Las herramientas Premium comienzan desde $19/mes.",
    "q_trial": "¿Ofrecen una prueba gratuita?",
    "a_trial": "Nuestro plan gratuito te da acceso indefinido a búsqueda de empleo, aplicaciones y tu panel.",
    "q_premium": "¿Qué incluye Premium?",
    "a_premium": "CVs y cartas ilimitados, ATS, preparación de entrevistas, análisis de brechas, Coach de Carrera y formato por país para EE.UU., UK, Canadá, Alemania y Francia — GPT-4o.",
    "q_resumeBuilder": "¿Cómo funciona el Constructor de CV con IA?",
    "a_resumeBuilder": "Dinos tu puesto objetivo, experiencia y habilidades. Nuestra IA genera un CV ATS-optimizado adaptado al país específico. Un CV para Alemania es muy distinto al de EE.UU.",
    "q_detector": "¿Qué es el Detector Remote-Friendly?",
    "a_detector": "Analiza cada oferta y muestra un badge de Probable / Incierto / Improbable para no perder tiempo en solicitudes equivocadas.",
    "q_skillGap": "¿Cómo funciona el Análisis de Brechas de Habilidades?",
    "a_skillGap": "Ingresa tu puesto y país objetivo. La IA identifica habilidades faltantes, certificaciones, expectativas de idioma y normas culturales.",
    "q_coverLetter": "¿Qué es el Generador de Cartas de Presentación IA?",
    "a_coverLetter": "Crea cartas personalizadas al tono profesional del país objetivo. Una carta para Alemania suena muy diferente a una para el Reino Unido.",
    "q_interviewPrep": "¿Qué es la Preparación para Entrevistas?",
    "a_interviewPrep": "Tu coach de entrevistas personal. Preguntas realistas con retroalimentación instantánea. Disponible 24/7.",
    "q_careerCoach": "¿Qué es el Coach de Carrera?",
    "a_careerCoach": "Análisis completo de tu perfil: puntuación ATS, brechas, referencias salariales y hoja de ruta personalizada. Disponible 24/7.",
    "q_copilot": "¿Cómo funciona el Copiloto?",
    "a_copilot": "Escribe en lenguaje sencillo lo que necesitas. El Copiloto te lleva directo a la herramienta correcta, pre-completada.",
    "q_countries": "¿Qué países están soportados?",
    "a_countries": "Optimizados para cinco mercados: EE.UU., Reino Unido, Canadá, Alemania y Francia. Más mercados próximamente.",
    "q_anywhere": "¿Puedo aplicar desde cualquier lugar?",
    "a_anywhere": "Absolutamente. Tu ubicación no es una barrera.",
    "q_fromOutside": "¿Puedo aplicar a trabajos desde fuera de mi país?",
    "a_fromOutside": "Absolutamente. Desde Asia, África, Latinoamérica o Europa del Este — puedes conseguir roles remotos en las mejores empresas del mundo.",
    "q_billing": "¿Cómo funciona la facturación?",
    "a_billing": "Premium a $19/mes. Cancela cuando quieras — sin contratos ni cargos.",
    "q_cancel": "¿Cómo cancelo mi suscripción?",
    "a_cancel": "En la configuración de tu cuenta, un clic. Acceso Premium completo hasta el final del ciclo.",
    "q_secure": "¿Son seguros mis datos?",
    "a_secure": "Protegidos con seguridad de nivel empresarial. Solo tú tienes acceso — nunca vendemos ni compartimos tus datos.",
    "q_support": "¿Cómo contacto al soporte?",
    "a_support": "Escríbenos a contact@jobconnect-ai.com — respondemos en menos de 24 horas."
  },
  "pt": {
    "greeting1": "👋 Olá! Sou o assistente JobConnect AI. Como posso ajudá-lo hoje?",
    "greeting2": "Escolha um tema abaixo ou faça sua pergunta.",
    "online": "Online",
    "repliesInstantly": "Geralmente responde instantaneamente",
    "poweredBy": "Desenvolvido por JobConnect AI",
    "minimize": "Minimizar chat",
    "expand": "Expandir visualização",
    "collapse": "Recolher visualização",
    "download": "Baixar transcrição",
    "newConversation": "Nova conversa",
    "transcriptTitle": "JobConnect AI - Transcrição do chat",
    "transcriptDate": "Data",
    "transcriptYou": "Você",
    "expandChat": "Maximizar",
    "reduceChat": "Restaurar",
    "themeGettingStarted": "Primeiros Passos",
    "themeAiTools": "Ferramentas de IA",
    "themeInternational": "Internacional",
    "themeBilling": "Faturamento & Conta",
    "themeSecurity": "Segurança & Suporte",
    "q_whatIs": "O que é o JobConnect AI?",
    "a_whatIs": "O JobConnect AI é um copiloto de carreira para profissionais internacionais que buscam empregos remotos além das fronteiras. Ferramentas de IA + vagas remotas curadas — tudo em um só lugar.",
    "q_whoFor": "Para quem é o JobConnect AI?",
    "a_whoFor": "Para profissionais ambiciosos que não deixam a geografia limitar sua carreira. De desenvolvedor no Vietnã a financeiro no Sudeste Asiático — esta plataforma foi criada para você.",
    "q_different": "O que diferencia o JobConnect AI do LinkedIn ou Indeed?",
    "a_different": "LinkedIn e Indeed são construídos país a país. O JobConnect AI foi criado do zero para o candidato transfronteiriço.",
    "q_free": "É gratuito?",
    "a_free": "Sim! Navegar pelas vagas e candidatar-se é gratuito para sempre. Ferramentas Premium começam a partir de $19/mês.",
    "q_trial": "Vocês oferecem avaliação gratuita?",
    "a_trial": "Nosso plano gratuito oferece navegação, candidaturas e painel indefinidamente.",
    "q_premium": "O que inclui o Premium?",
    "a_premium": "CVs e cartas ilimitados, ATS, Preparação para Entrevistas, Análise de Lacunas, Coach de Carreira e formatação por país para EUA, UK, Canadá, Alemanha e França — GPT-4o.",
    "q_resumeBuilder": "Como funciona o Construtor de CV?",
    "a_resumeBuilder": "Informe cargo alvo, experiência e habilidades. Nosso AI gera um CV ATS-otimizado para o país específico. Um CV para a Alemanha é muito diferente do americano.",
    "q_detector": "O que é o Detector Remote-Friendly?",
    "a_detector": "Analisa cada vaga e exibe um badge Provável / Incerto / Improvável para não perder tempo nas candidaturas erradas.",
    "q_skillGap": "Como funciona a Análise de Lacunas de Habilidades?",
    "a_skillGap": "Informe cargo e país alvo. Nosso AI identifica habilidades ausentes, certificações, expectativas de idioma e normas culturais.",
    "q_coverLetter": "O que é o Gerador de Carta de Apresentação?",
    "a_coverLetter": "Cria cartas personalizadas ao tom profissional do país alvo. Uma carta para empresa alemã soa muito diferente da britânica.",
    "q_interviewPrep": "O que é a Preparação para Entrevistas?",
    "a_interviewPrep": "Seu coach de entrevistas AI pessoal. Perguntas realistas com feedback instantâneo. Disponível 24/7.",
    "q_careerCoach": "O que é o Coach de Carreira?",
    "a_careerCoach": "Análise completa do perfil: ATS, lacunas, benchmarks salariais e roteiro personalizado. Conselheiro sênior disponível 24/7.",
    "q_copilot": "Como funciona o Copiloto?",
    "a_copilot": "Digite em linguagem simples o que precisa. O Copiloto AI te leva direto à ferramenta certa, pré-preenchida.",
    "q_countries": "Quais países são suportados?",
    "a_countries": "Otimizados para cinco mercados: EUA, UK, Canadá, Alemanha e França. Mais mercados em breve.",
    "q_anywhere": "Posso candidatar-me de qualquer lugar?",
    "a_anywhere": "Absolutamente. Sua localização não é uma barreira.",
    "q_fromOutside": "Posso candidatar-me a empregos de fora do meu país?",
    "a_fromOutside": "Absolutamente. Da Ásia, África, América Latina ou Europa Oriental — você pode conseguir vagas remotas nas melhores empresas do mundo.",
    "q_billing": "Como funciona o faturamento?",
    "a_billing": "Premium a $19/mês. Cancele quando quiser — sem contratos ou taxas.",
    "q_cancel": "Como cancelo minha assinatura?",
    "a_cancel": "Nas configurações da conta, um clique. Acesso Premium completo até o fim do ciclo.",
    "q_secure": "Meus dados estão seguros?",
    "a_secure": "Protegidos com segurança de nível empresarial. Só você tem acesso — nunca vendemos nem compartilhamos seus dados.",
    "q_support": "Como contato o suporte?",
    "a_support": "Envie e-mail para contact@jobconnect-ai.com — respondemos em até 24 horas."
  },
  "ar": {
    "greeting1": "👋 مرحباً! أنا مساعد JobConnect AI. كيف يمكنني مساعدتك اليوم؟",
    "greeting2": "اختر موضوعاً أدناه أو اكتب سؤالك.",
    "online": "متصل",
    "repliesInstantly": "يرد عادةً على الفور",
    "poweredBy": "مدعوم من JobConnect AI",
    "minimize": "تصغير المحادثة",
    "expand": "توسيع العرض",
    "collapse": "طي العرض",
    "download": "تنزيل النص",
    "newConversation": "محادثة جديدة",
    "transcriptTitle": "JobConnect AI - نص المحادثة",
    "transcriptDate": "التاريخ",
    "transcriptYou": "أنت",
    "expandChat": "تكبير",
    "reduceChat": "استعادة",
    "themeGettingStarted": "البدء",
    "themeAiTools": "أدوات الذكاء الاصطناعي",
    "themeInternational": "دولي",
    "themeBilling": "الفوترة والحساب",
    "themeSecurity": "الأمان والدعم",
    "q_whatIs": "ما هو JobConnect AI؟",
    "a_whatIs": "JobConnect AI مساعد مهني للمحترفين الدوليين الباحثين عن عمل عن بُعد عبر الحدود. أدوات ذكاء اصطناعي + لوحة وظائف عن بُعد — كل شيء في مكان واحد.",
    "q_whoFor": "لمن صُمّم JobConnect AI؟",
    "a_whoFor": "للمحترفين الطموحين الذين يرفضون تقييد مسيرتهم جغرافياً. من مطور في فيتنام يستهدف برلين إلى متخصص مالي في آسيا يتطلع إلى كندا — هذه المنصة بُنيت لك.",
    "q_different": "ما الذي يميز JobConnect AI عن LinkedIn أو Indeed؟",
    "a_different": "LinkedIn وIndeed مبنيان بلداً بلد. JobConnect AI مبني للباحث عن عمل عبر الحدود.",
    "q_free": "هل هو مجاني؟",
    "a_free": "نعم! التصفح والتقديم مجاني للأبد. الأدوات المميزة تبدأ من 19 دولاراً/شهرياً.",
    "q_trial": "هل توفرون تجربة مجانية؟",
    "a_trial": "خطتنا المجانية تمنحك تصفح الوظائف والتقديم ولوحة التحكم — إلى أجل غير مسمى.",
    "q_premium": "ما الذي يتضمنه Premium؟",
    "a_premium": "سير ذاتية وخطابات غير محدودة، ATS، تحضير المقابلات، تحليل الفجوات، مدرب المسيرة، وتنسيق خاص للولايات المتحدة والمملكة المتحدة وكندا وألمانيا وفرنسا — GPT-4o.",
    "q_resumeBuilder": "كيف يعمل منشئ السيرة الذاتية؟",
    "a_resumeBuilder": "أخبرنا بوظيفتك وخبرتك ومهاراتك. يولّد الذكاء الاصطناعي سيرة محسّنة للدولة المستهدفة. السيرة لألمانيا مختلفة تماماً عن الولايات المتحدة.",
    "q_detector": "ما هو كاشف Remote-Friendly؟",
    "a_detector": "يحلل كل إعلان ويعرض شارة محتمل / غير واضح / غير محتمل لتوفير وقتك.",
    "q_skillGap": "كيف يعمل تحليل الفجوات في المهارات؟",
    "a_skillGap": "أدخل وظيفتك ودولتك. الذكاء الاصطناعي يحدد المهارات المفقودة والشهادات وتوقعات اللغة والأعراف الثقافية.",
    "q_coverLetter": "ما هو منشئ خطاب التقديم؟",
    "a_coverLetter": "ينشئ خطابات مخصصة للنبرة المهنية للدولة المستهدفة. خطاب للشركات الألمانية مختلف تماماً عن البريطانية.",
    "q_interviewPrep": "ما هو التحضير للمقابلة؟",
    "a_interviewPrep": "مدرب المقابلات AI الشخصي. أسئلة واقعية مع ملاحظات فورية. متاح 24/7.",
    "q_careerCoach": "ما هو مدرب المسيرة المهنية؟",
    "a_careerCoach": "تحليل شامل: درجة ATS، فجوات المهارات، مقاييس الرواتب، وخارطة طريق مخصصة. متاح 24/7.",
    "q_copilot": "كيف يعمل المساعد الذكي؟",
    "a_copilot": "اكتب ما تحتاجه بلغة بسيطة. يأخذك مباشرة للأداة الصحيحة، محشوة مسبقاً.",
    "q_countries": "ما الدول المدعومة؟",
    "a_countries": "محسّن لخمسة أسواق: الولايات المتحدة، المملكة المتحدة، كندا، ألمانيا، فرنسا. أسواق إضافية قادمة.",
    "q_anywhere": "هل يمكنني التقديم من أي مكان؟",
    "a_anywhere": "بالتأكيد. موقعك ليس عائقاً.",
    "q_fromOutside": "هل يمكنني التقديم من خارج دولتي؟",
    "a_fromOutside": "بالتأكيد. من آسيا أو أفريقيا أو أمريكا اللاتينية أو أوروبا الشرقية — يمكنك الحصول على وظائف عن بُعد في أفضل الشركات.",
    "q_billing": "كيف تعمل الفوترة؟",
    "a_billing": "19 دولار/شهرياً. إلغاء في أي وقت — بلا عقود أو رسوم.",
    "q_cancel": "كيف أُلغي اشتراكي؟",
    "a_cancel": "من إعدادات حسابك بنقرة واحدة. تحتفظ بالوصول حتى نهاية دورة الفوترة.",
    "q_secure": "هل بياناتي آمنة؟",
    "a_secure": "محمية بأمان مؤسسي. لا يصل إليها إلا أنت — لا نبيعها ولا نشاركها.",
    "q_support": "كيف أتواصل مع الدعم؟",
    "a_support": "راسلنا على contact@jobconnect-ai.com — نرد خلال 24 ساعة."
  },
  "zh": {
    "greeting1": "👋 您好！我是 JobConnect AI 助手。今天我能为您提供什么帮助？",
    "greeting2": "请在下方选择主题或输入您的问题。",
    "online": "在线",
    "repliesInstantly": "通常即时回复",
    "poweredBy": "由 JobConnect AI 驱动",
    "minimize": "最小化聊天",
    "expand": "展开视图",
    "collapse": "收起视图",
    "download": "下载对话记录",
    "newConversation": "新对话",
    "transcriptTitle": "JobConnect AI - 聊天记录",
    "transcriptDate": "日期",
    "transcriptYou": "您",
    "expandChat": "最大化",
    "reduceChat": "还原",
    "themeGettingStarted": "快速入门",
    "themeAiTools": "AI 工具",
    "themeInternational": "国际求职",
    "themeBilling": "账单与账户",
    "themeSecurity": "安全与支持",
    "q_whatIs": "什么是 JobConnect AI？",
    "a_whatIs": "JobConnect AI 是专为跨境远程求职国际专业人士打造的职业副驾驶。AI 工具 + 精选远程职位 — 一站式解决方案。",
    "q_whoFor": "JobConnect AI 适合谁？",
    "a_whoFor": "专为不愿受地理限制的雄心勃勃专业人士打造。无论是瞄准柏林初创的越南开发者，还是意向加拿大企业的东南亚金融专家 — 这个平台就是为您而建。",
    "q_different": "JobConnect AI 与 LinkedIn 或 Indeed 有何不同？",
    "a_different": "LinkedIn 和 Indeed 按国家构建。JobConnect AI 从零开始专为跨境求职者打造。",
    "q_free": "是免费的吗？",
    "a_free": "是的！浏览职位和申请永久免费。高级 AI 工具起价 $19/月。",
    "q_trial": "有免费试用吗？",
    "a_trial": "免费计划提供无限期的职位浏览、申请和候选人仪表板。",
    "q_premium": "Premium 包含什么？",
    "a_premium": "无限 AI 简历和求职信、ATS 评分、面试准备、技能差距分析、职业教练，以及美国、英国、加拿大、德国、法国专属格式 — GPT-4o 驱动。",
    "q_resumeBuilder": "AI 简历生成器如何运作？",
    "a_resumeBuilder": "告诉我们目标职位、经验和技能。AI 生成针对目标国家优化的 ATS 简历。德国简历与美国截然不同。",
    "q_detector": "远程友好检测器是什么？",
    "a_detector": "分析每个职位，显示可能/不确定/不太可能标签，让您不在错误申请上浪费时间。",
    "q_skillGap": "技能差距分析如何运作？",
    "a_skillGap": "输入目标职位和国家。AI 识别缺失技能、认可证书、语言要求和文化规范。",
    "q_coverLetter": "AI 求职信生成器是什么？",
    "a_coverLetter": "创建符合目标国家专业语气的个性化求职信。德国与英国公司的求职信截然不同。",
    "q_interviewPrep": "面试准备是什么？",
    "a_interviewPrep": "个人 AI 面试教练。逼真问题与即时详细反馈。全天候可用。",
    "q_careerCoach": "职业教练是什么？",
    "a_careerCoach": "全面分析职业档案：ATS 评分、技能差距、薪资基准和个性化路线图。随时可用的高级职业顾问。",
    "q_copilot": "副驾驶如何运作？",
    "a_copilot": "用自然语言输入需求。AI 副驾驶直接带您到正确工具，预填好内容。",
    "q_countries": "支持哪些国家？",
    "a_countries": "针对五大市场优化：美国、英国、加拿大、德国和法国。更多市场即将推出。",
    "q_anywhere": "可以从任何地方申请吗？",
    "a_anywhere": "当然。您的地理位置不是障碍。",
    "q_fromOutside": "可以从国外申请工作吗？",
    "a_fromOutside": "当然。无论在亚洲、非洲、拉美还是东欧 — 都可以获得全球顶级公司的远程职位。",
    "q_billing": "账单如何运作？",
    "a_billing": "$19/月，随时可取消 — 无合同，无取消费用。",
    "q_cancel": "如何取消订阅？",
    "a_cancel": "账户设置一键取消。保留 Premium 访问权限至账单周期结束。",
    "q_secure": "数据安全吗？",
    "a_secure": "企业级行级安全保护。只有您可以访问 — 绝不出售或共享您的数据。",
    "q_support": "如何联系支持？",
    "a_support": "发送邮件至 contact@jobconnect-ai.com — 通常 24 小时内回复。"
  },
  "ja": {
    "greeting1": "👋 こんにちは！JobConnect AI アシスタントです。本日はどのようなお手伝いができますか？",
    "greeting2": "以下からトピックを選ぶか、ご質問を入力してください。",
    "online": "オンライン",
    "repliesInstantly": "通常すぐに返答します",
    "poweredBy": "JobConnect AI 提供",
    "minimize": "チャットを最小化",
    "expand": "ビューを拡大",
    "collapse": "ビューを縮小",
    "download": "トランスクリプトをダウンロード",
    "newConversation": "新しい会話",
    "transcriptTitle": "JobConnect AI - チャット記録",
    "transcriptDate": "日付",
    "transcriptYou": "あなた",
    "expandChat": "最大化",
    "reduceChat": "元に戻す",
    "themeGettingStarted": "はじめに",
    "themeAiTools": "AIツール",
    "themeInternational": "海外求職",
    "themeBilling": "請求・アカウント",
    "themeSecurity": "セキュリティ・サポート",
    "q_whatIs": "JobConnect AI とは何ですか？",
    "a_whatIs": "国境を越えてリモートワークを探す国際的なプロフェッショナルのためのキャリアコパイロット。AI搭載ツール＋厳選されたリモート求人ボード — すべてひとつの場所に。",
    "q_whoFor": "誰のためのサービスですか？",
    "a_whoFor": "地理的制限にキャリアを縛られたくない意欲的なプロフェッショナルのため。ベルリンのスタートアップを目指すベトナムの開発者にも、カナダ企業を狙う東南アジアの金融専門家にも — この platform はあなたのために作られました。",
    "q_different": "LinkedIn や Indeed との違いは？",
    "a_different": "LinkedIn と Indeed は国ごとに構築されています。JobConnect AI はクロスボーダーな求職者のために一から設計されました。",
    "q_free": "無料ですか？",
    "a_free": "はい！求人閲覧と応募は永久無料。プレミアムAIツールは月19ドルから。",
    "q_trial": "無料トライアルはありますか？",
    "a_trial": "無料プランで求人閲覧、応募、候補者ダッシュボードを無期限利用できます。",
    "q_premium": "プレミアムに含まれるものは？",
    "a_premium": "無制限のAI履歴書・カバーレター、ATSスコア、面接対策、スキルギャップ分析、キャリアコーチ、米国・英国・カナダ・ドイツ・フランスの国別フォーマット — GPT-4o動作。",
    "q_resumeBuilder": "AI履歴書ビルダーは？",
    "a_resumeBuilder": "希望職種・経験・スキルを入力。AIが目標国に合わせたATS最適化履歴書を生成。ドイツ向けと米国向けは大きく異なります。",
    "q_detector": "リモートフレンドリー検出器とは？",
    "a_detector": "各求人を分析し、可能性高い / 不明確 / 可能性低いバッジを表示。間違った応募に時間を無駄にしません。",
    "q_skillGap": "スキルギャップ分析は？",
    "a_skillGap": "希望職種と国を入力。AIが不足スキル、関連資格、言語要件、文化規範を特定します。",
    "q_coverLetter": "AIカバーレタージェネレーターとは？",
    "a_coverLetter": "目標国のプロトーンに合わせた個別カバーレターを作成。ドイツ企業向けは英国企業向けとは大きく異なります。",
    "q_interviewPrep": "面接対策とは？",
    "a_interviewPrep": "AI面接コーチ。行動・技術・状況の質問に対する即時フィードバック。24時間365日利用可能。",
    "q_careerCoach": "キャリアコーチとは？",
    "a_careerCoach": "プロフィールの総合分析：ATSスコア、スキルギャップ、給与ベンチマーク、パーソナライズされたロードマップ。24時間利用可能。",
    "q_copilot": "コパイロットは？",
    "a_copilot": "自然な言葉で入力するだけ。AIコパイロットが直接適切なツールに案内します。",
    "q_countries": "対応国は？",
    "a_countries": "5つの主要市場に完全対応：米国、英国、カナダ、ドイツ、フランス。追加市場も近日公開予定。",
    "q_anywhere": "どこからでも応募できますか？",
    "a_anywhere": "もちろん。あなたの場所は障壁ではありません。",
    "q_fromOutside": "自国以外から応募できますか？",
    "a_fromOutside": "もちろん。アジア、アフリカ、中南米、東欧からでもトップ企業のリモートポジションを獲得できます。",
    "q_billing": "請求の仕組みは？",
    "a_billing": "月額19ドル。いつでもキャンセル可能 — 契約なし、キャンセル料なし。",
    "q_cancel": "サブスクリプションキャンセル方法は？",
    "a_cancel": "アカウント設定からワンクリック。請求サイクル終了までフルアクセスを保持。",
    "q_secure": "データは安全ですか？",
    "a_secure": "行レベルセキュリティのエンタープライズグレード保護。あなただけがアクセス可能。",
    "q_support": "サポートへの連絡方法は？",
    "a_support": "contact@jobconnect-ai.com にメールを。通常24時間以内に返答します。"
  },
  "ko": {
    "greeting1": "👋 안녕하세요! JobConnect AI 어시스턴트입니다. 오늘 어떻게 도와드릴까요?",
    "greeting2": "아래에서 주제를 선택하거나 질문을 입력하세요.",
    "online": "온라인",
    "repliesInstantly": "보통 즉시 응답합니다",
    "poweredBy": "JobConnect AI 제공",
    "minimize": "채팅 최소화",
    "expand": "뷰 확장",
    "collapse": "뷰 축소",
    "download": "대화록 다운로드",
    "newConversation": "새 대화",
    "transcriptTitle": "JobConnect AI - 채팅 대화록",
    "transcriptDate": "날짜",
    "transcriptYou": "나",
    "expandChat": "최대화",
    "reduceChat": "복원",
    "themeGettingStarted": "시작하기",
    "themeAiTools": "AI 도구",
    "themeInternational": "국제 취업",
    "themeBilling": "결제 및 계정",
    "themeSecurity": "보안 및 지원",
    "q_whatIs": "JobConnect AI가 무엇인가요?",
    "a_whatIs": "국경을 초월한 원격 일자리를 찾는 국제 전문가를 위한 커리어 코파일럿. AI 기반 도구 + 엄선된 원격 채용 게시판 — 한 곳에서 모두 해결.",
    "q_whoFor": "누구를 위한 것인가요?",
    "a_whoFor": "지리적 제약이 커리어를 제한하도록 내버려 두지 않는 야심찬 전문가를 위해. 이 플랫폼은 당신을 위해 만들어졌습니다.",
    "q_different": "LinkedIn이나 Indeed와 다른 점은?",
    "a_different": "LinkedIn과 Indeed는 국가별로 구축됩니다. JobConnect AI는 처음부터 국경을 넘는 구직자를 위해 설계되었습니다.",
    "q_free": "무료인가요?",
    "a_free": "네! 채용 탐색과 지원은 영구 무료. 프리미엄 AI 도구는 월 $19부터.",
    "q_trial": "무료 체험이 있나요?",
    "a_trial": "무료 플랜으로 채용 탐색, 지원, 후보자 대시보드를 무기한 사용할 수 있습니다.",
    "q_premium": "프리미엄에는 무엇이 포함되나요?",
    "a_premium": "무제한 AI 이력서 및 커버레터, ATS 채점, 면접 준비, 역량 격차 분석, 커리어 코치, 미국·영국·캐나다·독일·프랑스 국가별 형식 — GPT-4o 구동.",
    "q_resumeBuilder": "AI 이력서 빌더는 어떻게 작동하나요?",
    "a_resumeBuilder": "목표 직무, 경력, 기술을 알려주세요. AI가 목표 국가에 맞는 ATS 최적화 이력서를 생성합니다. 독일용과 미국용은 크게 다릅니다.",
    "q_detector": "원격 친화 감지기란?",
    "a_detector": "각 채용 공고를 분석해 가능성 높음 / 불분명 / 가능성 낮음 배지를 표시합니다.",
    "q_skillGap": "역량 격차 분석은 어떻게 작동하나요?",
    "a_skillGap": "목표 직무와 국가를 입력하면 부족한 기술, 자격증, 언어 요건, 문화 규범을 파악합니다.",
    "q_coverLetter": "AI 커버레터 생성기란?",
    "a_coverLetter": "목표 국가의 전문적 어조에 맞는 개인화된 커버레터를 작성합니다.",
    "q_interviewPrep": "면접 준비란?",
    "a_interviewPrep": "개인 AI 면접 코치. 즉각적인 피드백. 24/7 이용 가능.",
    "q_careerCoach": "커리어 코치란?",
    "a_careerCoach": "종합 프로필 분석: ATS 점수, 역량 격차, 급여 벤치마크, 맞춤형 로드맵. 24/7 가능.",
    "q_copilot": "코파일럿은 어떻게 작동하나요?",
    "a_copilot": "자연어로 입력하면 AI가 미리 채워진 올바른 도구로 안내합니다.",
    "q_countries": "어떤 국가를 지원하나요?",
    "a_countries": "5개 주요 시장 완전 지원: 미국, 영국, 캐나다, 독일, 프랑스. 추가 시장 곧 제공.",
    "q_anywhere": "어디서든 지원할 수 있나요?",
    "a_anywhere": "물론입니다. 위치는 장벽이 아닙니다.",
    "q_fromOutside": "자국 외부에서 지원할 수 있나요?",
    "a_fromOutside": "물론입니다. 아시아, 아프리카, 남미, 동유럽 어디서도 글로벌 원격 직무를 획득할 수 있습니다.",
    "q_billing": "결제는 어떻게 이루어지나요?",
    "a_billing": "월 $19 청구. 언제든지 해지 가능 — 계약 없음, 수수료 없음.",
    "q_cancel": "구독을 어떻게 취소하나요?",
    "a_cancel": "계정 설정에서 원클릭 취소. 청구 주기 종료까지 전체 프리미엄 이용 권한 유지.",
    "q_secure": "내 데이터는 안전한가요?",
    "a_secure": "행 수준 보안의 기업급 보호. 본인만 접근 가능 — 데이터를 절대 판매·공유하지 않습니다.",
    "q_support": "고객 지원에 어떻게 연락하나요?",
    "a_support": "contact@jobconnect-ai.com으로 이메일 — 보통 24시간 내 답변."
  },
  "vi": {
    "greeting1": "👋 Xin chào! Tôi là trợ lý JobConnect AI. Tôi có thể giúp gì cho bạn hôm nay?",
    "greeting2": "Chọn chủ đề bên dưới hoặc nhập câu hỏi của bạn.",
    "online": "Trực tuyến",
    "repliesInstantly": "Thường trả lời ngay lập tức",
    "poweredBy": "Được hỗ trợ bởi JobConnect AI",
    "minimize": "Thu nhỏ chat",
    "expand": "Mở rộng giao diện",
    "collapse": "Thu gọn giao diện",
    "download": "Tải bản ghi cuộc trò chuyện",
    "newConversation": "Cuộc trò chuyện mới",
    "transcriptTitle": "JobConnect AI - Bản ghi cuộc trò chuyện",
    "transcriptDate": "Ngày",
    "transcriptYou": "Bạn",
    "expandChat": "Phóng to",
    "reduceChat": "Khôi phục",
    "themeGettingStarted": "Bắt đầu",
    "themeAiTools": "Công cụ AI",
    "themeInternational": "Quốc tế",
    "themeBilling": "Thanh toán & Tài khoản",
    "themeSecurity": "Bảo mật & Hỗ trợ",
    "q_whatIs": "JobConnect AI là gì?",
    "a_whatIs": "JobConnect AI là người đồng hành sự nghiệp cho chuyên gia quốc tế tìm việc từ xa xuyên biên giới. Công cụ AI + bảng việc làm từ xa được tuyển chọn — tất cả trong một nơi.",
    "q_whoFor": "JobConnect AI dành cho ai?",
    "a_whoFor": "Dành cho chuyên gia tham vọng không muốn để địa lý giới hạn sự nghiệp. Nền tảng này được xây dựng cho bạn nếu bạn theo đuổi sự nghiệp từ xa vượt biên giới.",
    "q_different": "JobConnect AI khác LinkedIn hay Indeed ở điểm nào?",
    "a_different": "LinkedIn và Indeed xây dựng theo từng quốc gia. JobConnect AI được xây dựng từ đầu dành riêng cho người tìm việc xuyên biên giới.",
    "q_free": "Có miễn phí không?",
    "a_free": "Có! Duyệt việc làm và ứng tuyển miễn phí mãi mãi. Công cụ AI Premium từ $19/tháng.",
    "q_trial": "Có dùng thử miễn phí không?",
    "a_trial": "Gói miễn phí cho phép duyệt việc, ứng tuyển và sử dụng bảng điều khiển vô thời hạn.",
    "q_premium": "Premium bao gồm những gì?",
    "a_premium": "CV và thư xin việc AI không giới hạn, ATS, Luyện phỏng vấn, Phân tích khoảng cách kỹ năng, Huấn luyện viên sự nghiệp, và định dạng theo quốc gia — GPT-4o.",
    "q_resumeBuilder": "Trình tạo CV AI hoạt động như thế nào?",
    "a_resumeBuilder": "Cho biết vị trí, kinh nghiệm và kỹ năng. AI tạo CV ATS-optimized theo quốc gia mục tiêu. CV cho Đức rất khác CV cho Mỹ.",
    "q_detector": "Bộ phát hiện Remote-Friendly là gì?",
    "a_detector": "Phân tích tin tuyển dụng và hiển thị badge Khả năng cao / Không rõ / Khả năng thấp.",
    "q_skillGap": "Phân tích khoảng cách kỹ năng hoạt động thế nào?",
    "a_skillGap": "Nhập vị trí và quốc gia mục tiêu. AI xác định kỹ năng thiếu, chứng chỉ, yêu cầu ngôn ngữ và chuẩn mực văn hóa.",
    "q_coverLetter": "Trình tạo Thư xin việc AI là gì?",
    "a_coverLetter": "Tạo thư xin việc cá nhân hóa theo tông chuyên nghiệp của quốc gia mục tiêu.",
    "q_interviewPrep": "Luyện phỏng vấn là gì?",
    "a_interviewPrep": "Coach phỏng vấn AI cá nhân. Câu hỏi thực tế với phản hồi chi tiết tức thì. 24/7.",
    "q_careerCoach": "Huấn luyện viên sự nghiệp là gì?",
    "a_careerCoach": "Phân tích toàn diện hồ sơ: ATS, khoảng cách kỹ năng, chuẩn mức lương, lộ trình cá nhân hóa. 24/7.",
    "q_copilot": "Copilot hoạt động thế nào?",
    "a_copilot": "Nhập điều cần trong ngôn ngữ thông thường. AI đưa bạn thẳng đến công cụ phù hợp, đã điền trước.",
    "q_countries": "Những quốc gia nào được hỗ trợ?",
    "a_countries": "Tối ưu cho 5 thị trường: Mỹ, Anh, Canada, Đức, Pháp. Thêm thị trường sắp ra mắt.",
    "q_anywhere": "Tôi có thể ứng tuyển từ bất cứ đâu không?",
    "a_anywhere": "Hoàn toàn có thể. Vị trí của bạn không phải rào cản.",
    "q_fromOutside": "Tôi có thể ứng tuyển từ ngoài nước không?",
    "a_fromOutside": "Hoàn toàn có thể. Từ châu Á, châu Phi, Mỹ Latin hay Đông Âu — bạn có thể nhận việc từ xa tại công ty hàng đầu thế giới.",
    "q_billing": "Thanh toán hoạt động thế nào?",
    "a_billing": "$19/tháng. Hủy bất cứ lúc nào — không hợp đồng, không phí hủy.",
    "q_cancel": "Làm thế nào để hủy đăng ký?",
    "a_cancel": "Cài đặt tài khoản, một cú nhấp. Toàn quyền truy cập Premium đến cuối chu kỳ thanh toán.",
    "q_secure": "Dữ liệu của tôi có an toàn không?",
    "a_secure": "Bảo vệ cấp doanh nghiệp với Row Level Security. Chỉ bạn mới có thể truy cập — không bao giờ bán hay chia sẻ dữ liệu.",
    "q_support": "Làm thế nào để liên hệ hỗ trợ?",
    "a_support": "Gửi email tới contact@jobconnect-ai.com — thường trả lời trong 24 giờ."
  },
  "ht": {
    "greeting1": "👋 Bonjou! Mwen se asistan JobConnect AI. Kijan mwen ka ede ou jodi a?",
    "greeting2": "Chwazi yon sijè anba a oswa ekri kesyon ou.",
    "online": "Anliy",
    "repliesInstantly": "Reponn anjeneral imedyatman",
    "poweredBy": "Alimante pa JobConnect AI",
    "minimize": "Minimize chat la",
    "expand": "Elaji vi a",
    "collapse": "Redui vi a",
    "download": "Telechaje transkripsyon an",
    "newConversation": "Nouvo konvesasyon",
    "transcriptTitle": "JobConnect AI - Transkripsyon Chat",
    "transcriptDate": "Dat",
    "transcriptYou": "Ou",
    "expandChat": "Maksimize",
    "reduceChat": "Retabli",
    "themeGettingStarted": "Komanse",
    "themeAiTools": "Zouti AI",
    "themeInternational": "Entenasyonal",
    "themeBilling": "Fakturation ak Kont",
    "themeSecurity": "Sekirite ak Sipò",
    "q_whatIs": "Ki sa JobConnect AI ye?",
    "a_whatIs": "JobConnect AI se yon kopilot karyè pou pwofesyonèl entènasyonal k ap chèche travay aleka atravè fwontyè. Zouti AI + tableau travay aleka seleksyone — tout nan yon sèl kote.",
    "q_whoFor": "Pou kiyès JobConnect AI ye?",
    "a_whoFor": "Pou pwofesyonèl anbisye ki refize kite jewografi limite karyè yo. Platfòm sa a bati pou ou.",
    "q_different": "Sa ki fè JobConnect AI diferan de LinkedIn oswa Indeed?",
    "a_different": "LinkedIn ak Indeed bati peyi pa peyi. JobConnect AI bati depi zewo pou moun k ap chèche travay atravè fwontyè.",
    "q_free": "Eske li gratis?",
    "a_free": "Wi! Navige pou travay ak aplike se gratis pou toujou. Zouti Premium kòmanse a $19/mwa.",
    "q_trial": "Eske nou ofri eseyi gratis?",
    "a_trial": "Plan gratis nou an ba ou navige, aplike, ak tablo bò san limit tan.",
    "q_premium": "Kisa Premium enkli?",
    "a_premium": "CV ak lèt motivasyon AI san limit, ATS, Preparasyon Entèvyou, Analiz Defisi, Coach Karyè, ak fòma espesifik pou Etazini, UK, Kanada, Almay ak Frans — GPT-4o.",
    "q_resumeBuilder": "Kijan Konstriktè CV AI travay?",
    "a_resumeBuilder": "Di nou wòl sib ou, eksperyans ak konpetans. AI jenere CV optimize pou peyi ou vize. Yon CV pou Almay diferan anpil de youn pou Etazini.",
    "q_detector": "Ki sa Detektè Remote-Friendly ye?",
    "a_detector": "Analize chak afich travay epi montre badj Pwobab / Pa kle / Pa pwobab pou ou pa pèdi tan sou move aplikasyon.",
    "q_skillGap": "Kijan Analiz Defisi Konpetans travay?",
    "a_skillGap": "Antre wòl sib ou ak peyi. AI idantifye konpetans ki manke, sètifikasyon, atant lang, ak nòm kiltirèl.",
    "q_coverLetter": "Ki sa Jeneratè Lèt Motivasyon AI ye?",
    "a_coverLetter": "Kreye lèt pèsonalize pou tòn pwofesyonèl peyi sib la. Yon lèt pou antrepriz Alman diferan de youn pou antrepriz Britanik.",
    "q_interviewPrep": "Ki sa Preparasyon Entèvyou ye?",
    "a_interviewPrep": "Coach entèvyou AI pèsonèl ou. Kesyon reyalis ak kòmantè detaye imedya. Disponib 24/7.",
    "q_careerCoach": "Ki sa Coach Karyè ye?",
    "a_careerCoach": "Analiz konplè pwofil ou: ATS, defisi, referans salè, ak fèy wout pèsonalize. Disponib 24/7.",
    "q_copilot": "Kijan Copilot la travay?",
    "a_copilot": "Ekri sa ou bezwen. AI mennen ou dirèkteman nan bon zouti a.",
    "q_countries": "Ki peyi ki sipòte?",
    "a_countries": "Optimize pou senk mache: Etazini, UK, Kanada, Almay, ak Frans. Lòt mache ap vini byento.",
    "q_anywhere": "Eske m ka aplike depi nenpòt kote?",
    "a_anywhere": "Absoliman. Kote ou ye pa yon baryè.",
    "q_fromOutside": "Eske m ka aplike depi deyò peyi mwen?",
    "a_fromOutside": "Absoliman. Depi Azi, Afrik, Amerik Latin, oswa Ewòp les — ou ka jwenn travay aleka nan pi bon antrepriz mondyal yo.",
    "q_billing": "Kijan fakturation travay?",
    "a_billing": "$19/mwa. Anile nenpòt ki le — pa gen kontra oswa frè.",
    "q_cancel": "Kijan pou m anile abonman mwen?",
    "a_cancel": "Anviwonman kont ou — yon klik. Aksè Premium konplè jiska fen sik fakturation.",
    "q_secure": "Eske done mwen yo an sekirite?",
    "a_secure": "Pwoteje ak sekirite nivo antrepriz. Sèlman ou ka aksede — nou pa janm vann oswa pataje done ou.",
    "q_support": "Kijan pou m kontakte sipò?",
    "a_support": "Voye imèl nan contact@jobconnect-ai.com — nou reponn nan 24 edtan."
  }
}

BASE = "/Users/stevensonjean-louis/Projects/jobconnect-ai/messages"

for locale, data in TRANSLATIONS.items():
    path = f"{BASE}/{locale}.json"
    with open(path) as f:
        obj = json.load(f)
    obj["chatWidget"] = data
    with open(path, "w") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
    print(f"✓ {locale}.json updated ({len(data)} keys)")

print("All done.")
